import withPWAInit from "next-pwa";
import defaultCache from "next-pwa/cache";

type WorkboxUrlPatternContext = {
  url: URL;
  request: Request;
  event?: unknown;
};

/**
 * Phase 15 PWA update policy.
 *
 * Important:
 * - public/sw.js is generated by next-pwa/Workbox. Do not hand-edit it.
 * - skipWaiting + clientsClaim activate a new deployment promptly.
 * - version.json is always fetched network-only by AppUpdateManager.
 * - IndexedDB is never cleared during an application update.
 */
const withPWA = withPWAInit({
  dest: "public",
  register: true,
  skipWaiting: true,
  disable: process.env.NODE_ENV === "development",
  cleanupOutdatedCaches: true,

  /**
   * Exclude version.json from the precache so the update manager always gets
   * the latest deployment metadata from the network.
   */
  buildExcludes: [
    /version\.json$/,
  ],

  runtimeCaching: [
    {
      urlPattern: ({
        url,
      }: WorkboxUrlPatternContext) =>
        url.origin ===
          self.location.origin &&
        url.pathname ===
          "/version.json",
      handler: "NetworkOnly",
      method: "GET",
    },

    /**
     * Preserve next-pwa's default caching for pages, Next assets, scripts,
     * styles, fonts, images and other application resources.
     */
    ...defaultCache,
  ],
});

const nextConfig = {
  reactStrictMode: true,

  env: {
    NEXT_PUBLIC_ELEEVEON_BUILD_ID:
      process.env.ELEEVEON_BUILD_ID ||
      process.env.VERCEL_GIT_COMMIT_SHA ||
      process.env.NEXT_PUBLIC_ELEEVEON_BUILD_ID ||
      "development",

    NEXT_PUBLIC_ELEEVEON_APP_VERSION:
      process.env.ELEEVEON_APP_VERSION ||
      process.env.npm_package_version ||
      process.env.NEXT_PUBLIC_ELEEVEON_APP_VERSION ||
      "0.0.0",

    NEXT_PUBLIC_ELEEVEON_MINIMUM_DB_VERSION:
      process.env.ELEEVEON_MINIMUM_DB_VERSION ||
      process.env.NEXT_PUBLIC_ELEEVEON_MINIMUM_DB_VERSION ||
      "39",

    NEXT_PUBLIC_ELEEVEON_CURRENT_DB_VERSION:
      process.env.ELEEVEON_CURRENT_DB_VERSION ||
      process.env.NEXT_PUBLIC_ELEEVEON_CURRENT_DB_VERSION ||
      "39",
  },
};

export default withPWA(nextConfig);