"use client";

import React from "react";

import type { ReportCardTemplateSetting } from "../../../../lib/db/db";
import type { ReportHeaderData } from "../engine/report-types";
import type { StudentCumulativeTranscript } from "../engine/cumulative-report-types";

type Props = {
  dataset?: {
    header?: ReportHeaderData;
    transcript?: StudentCumulativeTranscript | null;
    generatedAt?: string | number | Date | null;
  } | null;
  header?: ReportHeaderData;
  transcript?: StudentCumulativeTranscript | null;
  settings?: Partial<ReportCardTemplateSetting> | null;
  compact?: boolean;
  showWatermark?: boolean;
  pageBreakAfter?: boolean;
};

const formatNumber = (value?: number | null, decimals = 1) => {
  if (value == null || Number.isNaN(Number(value))) return "-";
  return Number(value).toFixed(decimals);
};

const formatDate = (value?: string | number | Date | null) => {
  if (!value) return "-";
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleDateString("en-GB", { year: "numeric", month: "short", day: "2-digit" });
};

const ordinal = (value?: number | null) => {
  if (!value) return "-";
  const suffixes = ["th", "st", "nd", "rd"];
  const mod100 = value % 100;
  return `${value}${suffixes[(mod100 - 20) % 10] || suffixes[mod100] || suffixes[0]}`;
};

const trendLabel = (trend?: string | null) => {
  if (trend === "up") return "Improving";
  if (trend === "down") return "Declining";
  if (trend === "stable") return "Stable";
  return "-";
};

const decisionLabel = (value?: string | null) => {
  if (!value) return "-";
  return value.charAt(0).toUpperCase() + value.slice(1);
};

const safeText = (...values: unknown[]) => {
  for (const value of values) {
    const text = String(value ?? "").trim();
    if (text) return text;
  }
  return "-";
};

function buildContext(props: Props) {
  const header = props.header || props.dataset?.header;
  const transcript = props.transcript ?? props.dataset?.transcript ?? null;
  const settings = props.settings || {};
  const branding = header?.branding || ({} as any);
  const primary = branding.primaryColor || "#111827";
  const generatedAt = props.dataset?.generatedAt || new Date();

  const labels = {
    student: settings.studentNameLabel || "Student",
    studentId: settings.admissionNumberLabel || "Student ID",
    gender: settings.genderLabel || "Gender",
    className: settings.classLabel || "Programme / Class",
    period: settings.academicPeriodLabel || "Academic Period",
    subject: settings.subjectLabel || "Course / Subject",
    total: settings.totalLabel || "Score",
    average: settings.averageLabel || "Average",
    grade: settings.gradeLabel || "Grade",
    position: settings.subjectPositionLabel || "Rank",
    classPosition: settings.classPositionLabel || "Cumulative Position",
    gpa: settings.gpaLabel || "GPA",
    generated: settings.generatedDateLabel || "Date Generated",
    footer: settings.footerText || "Official cumulative academic transcript generated by Eleeveon Schools.",
  };

  return { header, transcript, settings, branding, primary, labels, generatedAt };
}

function EmptyTranscript({ header, title, primary, compact, pageBreakAfter }: { header?: ReportHeaderData; title: string; primary: string; compact: boolean; pageBreakAfter: boolean }) {
  const branding = header?.branding || ({} as any);
  return (
    <section
      className="print-page report-page-break cumulative-transcript-page"
      style={{
        width: "210mm",
        minHeight: "297mm",
        margin: "0 auto 20px",
        padding: compact ? "9mm" : "11mm",
        boxSizing: "border-box",
        background: "#fff",
        color: "#111827",
        fontFamily: branding.fontFamily || "Arial, sans-serif",
        border: "1px solid #d1d5db",
        pageBreakAfter: pageBreakAfter ? "always" : "auto",
      }}
    >
      <div style={{ borderBottom: `3px solid ${primary}`, paddingBottom: 8, marginBottom: 16 }}>
        <div style={{ fontSize: compact ? 15 : 18, fontWeight: 950, textTransform: "uppercase" }}>{safeText(branding.schoolName, "School")}</div>
        <div style={{ fontSize: 10, fontWeight: 800, color: "#4b5563" }}>{title}</div>
      </div>
      <div style={{ border: "1px dashed #9ca3af", padding: 18, textAlign: "center", fontWeight: 800, borderRadius: 10 }}>
        Select a student with historical report snapshots to generate a cumulative academic transcript.
      </div>
    </section>
  );
}

export default function CumulativeTranscriptCompact(props: Props) {
  const { header, transcript, settings, branding, primary, labels, generatedAt } = buildContext(props);
  const compact = true;
  const pageBreakAfter = props.pageBreakAfter ?? true;

  if (!transcript) {
    return <EmptyTranscript header={header} title="Compact Cumulative Transcript" primary={primary} compact={compact} pageBreakAfter={pageBreakAfter} />;
  }

  const page: React.CSSProperties = { width: "210mm", minHeight: "297mm", margin: "0 auto 20px", padding: "7mm", boxSizing: "border-box", background: "#fff", color: "#111", fontFamily: branding.fontFamily || "Arial, sans-serif", border: "1px solid #d1d5db", pageBreakAfter: pageBreakAfter ? "always" : "auto" };
  const table: React.CSSProperties = { width: "100%", borderCollapse: "collapse", fontSize: 7.4 };
  const th: React.CSSProperties = { border: "1px solid #111", padding: 2.5, background: primary, color: "#fff", fontWeight: 900, textAlign: "center" };
  const td: React.CSSProperties = { border: "1px solid #555", padding: 2.5, verticalAlign: "top", lineHeight: 1.12 };

  return (
    <section className="print-page report-page-break cumulative-transcript-page cumulative-transcript-compact" style={page}>
      <header style={{ display: "flex", justifyContent: "space-between", gap: 10, alignItems: "flex-start", borderBottom: "2px solid #111", paddingBottom: 5 }}>
        <div><div style={{ fontSize: 13, fontWeight: 950, textTransform: "uppercase" }}>{safeText(branding.schoolName, "School")}</div><div style={{ fontSize: 7.2 }}>{[branding.branchName, branding.phone, branding.email].filter(Boolean).join(" • ")}</div></div>
        <div style={{ textAlign: "right", fontSize: 8, fontWeight: 950, textTransform: "uppercase" }}>Cumulative Transcript</div>
      </header>
      <div style={{ marginTop: 5, display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr", gap: 3, fontSize: 7.4 }}>
        <div><strong>{labels.student}:</strong> {transcript.studentName}</div><div><strong>ID:</strong> {transcript.admissionNumber || "-"}</div><div><strong>Class:</strong> {transcript.currentClassName || "-"}</div><div><strong>Avg:</strong> {formatNumber(transcript.cumulativeAverage, 1)}%</div><div><strong>GPA:</strong> {transcript.cumulativeGPA != null ? formatNumber(transcript.cumulativeGPA, 2) : "-"}</div>
      </div>
      <table style={{ ...table, marginTop: 5 }}>
        <thead><tr><th style={{ ...th, textAlign: "left", width: 76 }}>Period</th><th style={{ ...th, textAlign: "left" }}>{labels.subject}</th><th style={th}>Score</th><th style={th}>%</th><th style={th}>{labels.grade}</th><th style={th}>Rank</th><th style={{ ...th, textAlign: "left" }}>Remark</th></tr></thead>
        <tbody>
          {transcript.periods.flatMap((period) => period.subjectResults.map((subject, index) => (
            <tr key={`${period.academicPeriodId}-${subject.subjectId || subject.subjectName}-${index}`}>
              <td style={td}>{index === 0 ? <><strong>{period.academicPeriodName}</strong><br />{period.className}<br />Avg: {formatNumber(period.average, 1)}%</> : ""}</td>
              <td style={{ ...td, fontWeight: 800 }}>{subject.subjectName}</td>
              <td style={{ ...td, textAlign: "center" }}>{formatNumber(subject.total ?? subject.weightedTotal ?? subject.percentage, 1)}</td>
              <td style={{ ...td, textAlign: "center" }}>{formatNumber(subject.percentage, 1)}</td>
              <td style={{ ...td, textAlign: "center", fontWeight: 900 }}>{subject.grade || "-"}</td>
              <td style={{ ...td, textAlign: "center" }}>{ordinal(subject.position)}</td>
              <td style={td}>{subject.remark || "-"}</td>
            </tr>
          )))}
        </tbody>
      </table>
      <div style={{ marginTop: 5, display: "grid", gridTemplateColumns: "repeat(6, 1fr)", border: "1px solid #111", fontSize: 7.2 }}>
        {[["Periods", transcript.totalPeriods], ["Subjects", transcript.totalSubjects], ["Cum Total", formatNumber(transcript.cumulativeTotal, 1)], ["Cum Avg", `${formatNumber(transcript.cumulativeAverage, 1)}%`], ["High", `${formatNumber(transcript.highestAverage, 1)}%`], ["Trend", trendLabel(transcript.overallTrend)]].map(([l, v], i) => <div key={String(l)} style={{ padding: 3, borderLeft: i ? "1px solid #111" : 0 }}><strong>{l}:</strong> {v}</div>)}
      </div>
      <footer style={{ marginTop: 5, display: "flex", justifyContent: "space-between", borderTop: "1px solid #111", paddingTop: 3, fontSize: 6.8 }}><span>{labels.footer}</span>{settings.showGeneratedDate !== false && <span>{labels.generated}: {formatDate(generatedAt)}</span>}</footer>
    </section>
  );
}
