"use client";

import React from "react";

import type { ReportCardTemplateSetting } from "../../../../lib/db";
import type { ReportHeaderData } from "../engine/report-types";
import type { StudentCumulativeTranscript } from "../engine/cumulative-report-types";

type Props = {
  dataset?: {
    header?: ReportHeaderData;
    transcript?: StudentCumulativeTranscript | null;
    generatedAt?: string | number | Date | null;
  } | null;
  header?: ReportHeaderData;
  transcript?: StudentCumulativeTranscript | null;
  settings?: Partial<ReportCardTemplateSetting> | null;
  compact?: boolean;
  showWatermark?: boolean;
  pageBreakAfter?: boolean;
};

const formatNumber = (value?: number | null, decimals = 1) => {
  if (value == null || Number.isNaN(Number(value))) return "-";
  return Number(value).toFixed(decimals);
};

const formatDate = (value?: string | number | Date | null) => {
  if (!value) return "-";
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleDateString("en-GB", { year: "numeric", month: "short", day: "2-digit" });
};

const ordinal = (value?: number | null) => {
  if (!value) return "-";
  const suffixes = ["th", "st", "nd", "rd"];
  const mod100 = value % 100;
  return `${value}${suffixes[(mod100 - 20) % 10] || suffixes[mod100] || suffixes[0]}`;
};

const trendLabel = (trend?: string | null) => {
  if (trend === "up") return "Improving";
  if (trend === "down") return "Declining";
  if (trend === "stable") return "Stable";
  return "-";
};

const decisionLabel = (value?: string | null) => {
  if (!value) return "-";
  return value.charAt(0).toUpperCase() + value.slice(1);
};

const safeText = (...values: unknown[]) => {
  for (const value of values) {
    const text = String(value ?? "").trim();
    if (text) return text;
  }
  return "-";
};

function buildContext(props: Props) {
  const header = props.header || props.dataset?.header;
  const transcript = props.transcript ?? props.dataset?.transcript ?? null;
  const settings = props.settings || {};
  const branding = header?.branding || ({} as any);
  const primary = branding.primaryColor || "#111827";
  const generatedAt = props.dataset?.generatedAt || new Date();

  const labels = {
    student: settings.studentNameLabel || "Student",
    studentId: settings.admissionNumberLabel || "Student ID",
    gender: settings.genderLabel || "Gender",
    className: settings.classLabel || "Programme / Class",
    period: settings.academicPeriodLabel || "Academic Period",
    subject: settings.subjectLabel || "Course / Subject",
    total: settings.totalLabel || "Score",
    average: settings.averageLabel || "Average",
    grade: settings.gradeLabel || "Grade",
    position: settings.subjectPositionLabel || "Rank",
    classPosition: settings.classPositionLabel || "Cumulative Position",
    gpa: settings.gpaLabel || "GPA",
    generated: settings.generatedDateLabel || "Date Generated",
    footer: settings.footerText || "Official cumulative academic transcript generated by Eleeveon Schools.",
  };

  return { header, transcript, settings, branding, primary, labels, generatedAt };
}

function EmptyTranscript({ header, title, primary, compact, pageBreakAfter }: { header?: ReportHeaderData; title: string; primary: string; compact: boolean; pageBreakAfter: boolean }) {
  const branding = header?.branding || ({} as any);
  return (
    <section
      className="print-page report-page-break cumulative-transcript-page"
      style={{
        width: "210mm",
        minHeight: "297mm",
        margin: "0 auto 20px",
        padding: compact ? "9mm" : "11mm",
        boxSizing: "border-box",
        background: "#fff",
        color: "#111827",
        fontFamily: branding.fontFamily || "Arial, sans-serif",
        border: "1px solid #d1d5db",
        pageBreakAfter: pageBreakAfter ? "always" : "auto",
      }}
    >
      <div style={{ borderBottom: `3px solid ${primary}`, paddingBottom: 8, marginBottom: 16 }}>
        <div style={{ fontSize: compact ? 15 : 18, fontWeight: 950, textTransform: "uppercase" }}>{safeText(branding.schoolName, "School")}</div>
        <div style={{ fontSize: 10, fontWeight: 800, color: "#4b5563" }}>{title}</div>
      </div>
      <div style={{ border: "1px dashed #9ca3af", padding: 18, textAlign: "center", fontWeight: 800, borderRadius: 10 }}>
        Select a student with historical report snapshots to generate a cumulative academic transcript.
      </div>
    </section>
  );
}

export default function CumulativeTranscriptOfficial(props: Props) {
  const { header, transcript, settings, branding, primary, labels, generatedAt } = buildContext(props);
  const compact = props.compact ?? false;
  const pageBreakAfter = props.pageBreakAfter ?? true;

  if (!transcript) {
    return <EmptyTranscript header={header} title="Official Academic Records" primary={primary} compact={compact} pageBreakAfter={pageBreakAfter} />;
  }

  const page: React.CSSProperties = {
    width: "210mm", minHeight: "297mm", margin: "0 auto 20px", padding: compact ? "8mm" : "10mm", boxSizing: "border-box",
    background: "#fff", color: "#000", fontFamily: branding.fontFamily || "Times New Roman, serif", border: "1px solid #9ca3af", pageBreakAfter: pageBreakAfter ? "always" : "auto",
  };
  const table: React.CSSProperties = { width: "100%", borderCollapse: "collapse", fontSize: compact ? 8 : 8.7 };
  const th: React.CSSProperties = { borderBottom: "1.5px solid #000", padding: "3px 4px", textAlign: "left", fontWeight: 900 };
  const td: React.CSSProperties = { padding: "2.5px 4px", verticalAlign: "top", lineHeight: 1.18 };

  return (
    <section className="print-page report-page-break cumulative-transcript-page cumulative-transcript-official" style={page}>
      <header style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: 12, borderBottom: "3px double #000", paddingBottom: 7 }}>
        <div>
          <div style={{ fontSize: compact ? 15 : 17, fontWeight: 900 }}>{safeText(branding.schoolName, "Institution")}</div>
          <div style={{ fontSize: compact ? 8 : 8.7, lineHeight: 1.25 }}>{[branding.address, branding.website, branding.email].filter(Boolean).join("\n")}</div>
        </div>
        <div style={{ textAlign: "right" }}>
          {branding.logo && <img src={branding.logo} alt="Institution logo" style={{ width: 42, height: 42, objectFit: "contain", marginBottom: 3 }} />}
          <div style={{ fontSize: compact ? 9 : 10, fontWeight: 900, textTransform: "uppercase" }}>Official Academic Records</div>
        </div>
      </header>

      <div style={{ marginTop: 8, fontSize: compact ? 8.5 : 9.2, lineHeight: 1.4 }}>
        <strong>{labels.student}:</strong> {transcript.studentName} &nbsp;&nbsp;
        <strong>{labels.studentId}:</strong> {transcript.admissionNumber || "-"} &nbsp;&nbsp;
        <strong>DOB/Gender:</strong> {transcript.gender || "-"} &nbsp;&nbsp;
        <strong>{labels.className}:</strong> {transcript.currentClassName || "-"}
      </div>

      <div style={{ marginTop: 10, fontWeight: 900, fontSize: compact ? 9 : 10 }}>Beginning of Academic Records</div>

      {transcript.periods.map((period) => (
        <div key={`${period.academicPeriodId}-${period.snapshotId || "official"}`} style={{ marginTop: 9, breakInside: "avoid" }}>
          <div style={{ fontSize: compact ? 9 : 10, fontWeight: 900 }}>{period.academicPeriodName}</div>
          <div style={{ fontSize: compact ? 7.6 : 8.2, marginBottom: 2 }}>{period.className}{period.academicYear ? ` • ${period.academicYear}` : ""}</div>
          <table style={table}>
            <thead><tr>
              <th style={{ ...th, width: 82 }}>Course Code</th>
              <th style={th}>Course Description</th>
              <th style={{ ...th, textAlign: "right" }}>Score</th>
              <th style={{ ...th, textAlign: "right" }}>%</th>
              <th style={{ ...th, textAlign: "right" }}>Quality Pts</th>
              <th style={{ ...th, textAlign: "center" }}>{labels.grade}</th>
            </tr></thead>
            <tbody>
              {period.subjectResults.map((subject) => {
                const qualityPoints = subject.gpa != null ? subject.gpa : undefined;
                return (
                  <tr key={`${period.academicPeriodId}-${subject.subjectId || subject.subjectName}`}>
                    <td style={td}>{subject.subjectCode || `SUB${subject.subjectId || ""}`}</td>
                    <td style={td}>{subject.subjectName}</td>
                    <td style={{ ...td, textAlign: "right" }}>{formatNumber(subject.total ?? subject.weightedTotal ?? subject.percentage, 1)}</td>
                    <td style={{ ...td, textAlign: "right" }}>{formatNumber(subject.percentage, 1)}</td>
                    <td style={{ ...td, textAlign: "right" }}>{qualityPoints != null ? formatNumber(qualityPoints, 2) : "-"}</td>
                    <td style={{ ...td, textAlign: "center", fontWeight: 900 }}>{subject.grade || "-"}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 3, fontSize: compact ? 8 : 8.6 }}>
            <div><strong>Term GPA:</strong> {period.gpa != null ? formatNumber(period.gpa, 3) : "-"}</div>
            <div><strong>Cum GPA:</strong> {transcript.cumulativeGPA != null ? formatNumber(transcript.cumulativeGPA, 3) : "-"}</div>
            <div><strong>Term Totals:</strong> {formatNumber(period.total, 1)} / {formatNumber(period.average, 1)}%</div>
            <div><strong>Cum Totals:</strong> {formatNumber(transcript.cumulativeTotal, 1)} / {formatNumber(transcript.cumulativeAverage, 1)}%</div>
          </div>
        </div>
      ))}

      <div style={{ marginTop: 12, borderTop: "1.5px solid #000", paddingTop: 6 }}>
        <div style={{ fontWeight: 900, fontSize: compact ? 9 : 10 }}>End of Transcript Statistics</div>
        <table style={{ ...table, marginTop: 3 }}><tbody>
          <tr><td style={td}>Institution</td><td style={td}>{transcript.cumulativeGPA != null ? formatNumber(transcript.cumulativeGPA, 3) : "-"}</td><td style={td}>{formatNumber(transcript.cumulativeAverage, 1)}%</td><td style={td}>{formatNumber(transcript.cumulativeTotal, 1)}</td></tr>
          <tr><td style={td}>Overall</td><td style={td}>{transcript.cumulativeGPA != null ? formatNumber(transcript.cumulativeGPA, 3) : "-"}</td><td style={td}>{formatNumber(transcript.cumulativeAverage, 1)}%</td><td style={td}>{trendLabel(transcript.overallTrend)}</td></tr>
        </tbody></table>
      </div>

      {settings.showTranscriptFinalRecommendation !== false && (
        <div style={{ marginTop: 8, fontSize: compact ? 8 : 8.6 }}><strong>Latest Decision:</strong> {decisionLabel(transcript.latestDecision)}</div>
      )}

      <footer style={{ marginTop: 14, borderTop: "1px solid #000", paddingTop: 4, display: "flex", justifyContent: "space-between", fontSize: 7.5 }}>
        <span>*** End of Transcript ***</span>
        {settings.showGeneratedDate !== false && <span>{labels.generated}: {formatDate(generatedAt)} &nbsp; Page 1 of 1</span>}
      </footer>
    </section>
  );
}
