"use client";

import React from "react";

import type { ReportCardTemplateSetting } from "../../../../lib/db";
import type { ReportHeaderData } from "../engine/report-types";
import type { StudentCumulativeTranscript } from "../engine/cumulative-report-types";

type Props = {
  dataset?: {
    header?: ReportHeaderData;
    transcript?: StudentCumulativeTranscript | null;
    generatedAt?: string | number | Date | null;
  } | null;
  header?: ReportHeaderData;
  transcript?: StudentCumulativeTranscript | null;
  settings?: Partial<ReportCardTemplateSetting> | null;
  compact?: boolean;
  showWatermark?: boolean;
  pageBreakAfter?: boolean;
};

const formatNumber = (value?: number | null, decimals = 1) => {
  if (value == null || Number.isNaN(Number(value))) return "-";
  return Number(value).toFixed(decimals);
};

const formatDate = (value?: string | number | Date | null) => {
  if (!value) return "-";
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleDateString("en-GB", { year: "numeric", month: "short", day: "2-digit" });
};

const ordinal = (value?: number | null) => {
  if (!value) return "-";
  const suffixes = ["th", "st", "nd", "rd"];
  const mod100 = value % 100;
  return `${value}${suffixes[(mod100 - 20) % 10] || suffixes[mod100] || suffixes[0]}`;
};

const trendLabel = (trend?: string | null) => {
  if (trend === "up") return "Improving";
  if (trend === "down") return "Declining";
  if (trend === "stable") return "Stable";
  return "-";
};

const decisionLabel = (value?: string | null) => {
  if (!value) return "-";
  return value.charAt(0).toUpperCase() + value.slice(1);
};

const safeText = (...values: unknown[]) => {
  for (const value of values) {
    const text = String(value ?? "").trim();
    if (text) return text;
  }
  return "-";
};

function buildContext(props: Props) {
  const header = props.header || props.dataset?.header;
  const transcript = props.transcript ?? props.dataset?.transcript ?? null;
  const settings = props.settings || {};
  const branding = header?.branding || ({} as any);
  const primary = branding.primaryColor || "#111827";
  const generatedAt = props.dataset?.generatedAt || new Date();

  const labels = {
    student: settings.studentNameLabel || "Student",
    studentId: settings.admissionNumberLabel || "Student ID",
    gender: settings.genderLabel || "Gender",
    className: settings.classLabel || "Programme / Class",
    period: settings.academicPeriodLabel || "Academic Period",
    subject: settings.subjectLabel || "Course / Subject",
    total: settings.totalLabel || "Score",
    average: settings.averageLabel || "Average",
    grade: settings.gradeLabel || "Grade",
    position: settings.subjectPositionLabel || "Rank",
    classPosition: settings.classPositionLabel || "Cumulative Position",
    gpa: settings.gpaLabel || "GPA",
    generated: settings.generatedDateLabel || "Date Generated",
    footer: settings.footerText || "Official cumulative academic transcript generated by Eleeveon Schools.",
  };

  return { header, transcript, settings, branding, primary, labels, generatedAt };
}

function EmptyTranscript({ header, title, primary, compact, pageBreakAfter }: { header?: ReportHeaderData; title: string; primary: string; compact: boolean; pageBreakAfter: boolean }) {
  const branding = header?.branding || ({} as any);
  return (
    <section
      className="print-page report-page-break cumulative-transcript-page"
      style={{
        width: "210mm",
        minHeight: "297mm",
        margin: "0 auto 20px",
        padding: compact ? "9mm" : "11mm",
        boxSizing: "border-box",
        background: "#fff",
        color: "#111827",
        fontFamily: branding.fontFamily || "Arial, sans-serif",
        border: "1px solid #d1d5db",
        pageBreakAfter: pageBreakAfter ? "always" : "auto",
      }}
    >
      <div style={{ borderBottom: `3px solid ${primary}`, paddingBottom: 8, marginBottom: 16 }}>
        <div style={{ fontSize: compact ? 15 : 18, fontWeight: 950, textTransform: "uppercase" }}>{safeText(branding.schoolName, "School")}</div>
        <div style={{ fontSize: 10, fontWeight: 800, color: "#4b5563" }}>{title}</div>
      </div>
      <div style={{ border: "1px dashed #9ca3af", padding: 18, textAlign: "center", fontWeight: 800, borderRadius: 10 }}>
        Select a student with historical report snapshots to generate a cumulative academic transcript.
      </div>
    </section>
  );
}

export default function CumulativeTranscriptClassic(props: Props) {
  const { header, transcript, settings, branding, primary, labels, generatedAt } = buildContext(props);
  const compact = props.compact ?? false;
  const pageBreakAfter = props.pageBreakAfter ?? true;
  const showWatermark = props.showWatermark !== false;

  if (!transcript) {
    return <EmptyTranscript header={header} title="Cumulative Academic Transcript" primary={primary} compact={compact} pageBreakAfter={pageBreakAfter} />;
  }

  const page: React.CSSProperties = {
    width: "210mm",
    minHeight: "297mm",
    margin: "0 auto 20px",
    padding: compact ? "9mm" : "11mm",
    boxSizing: "border-box",
    background: "#fff",
    color: "#111827",
    fontFamily: branding.fontFamily || "Arial, sans-serif",
    border: "1px solid #d1d5db",
    position: "relative",
    overflow: "hidden",
    pageBreakAfter: pageBreakAfter ? "always" : "auto",
  };

  const table: React.CSSProperties = { width: "100%", borderCollapse: "collapse", fontSize: compact ? 8.4 : 9.2 };
  const th: React.CSSProperties = { border: "1px solid #111827", padding: compact ? 3 : 5, background: primary, color: "#fff", textAlign: "center", fontWeight: 900 };
  const td: React.CSSProperties = { border: "1px solid #374151", padding: compact ? 3 : 5, verticalAlign: "top", lineHeight: 1.25 };
  const label: React.CSSProperties = { fontSize: compact ? 7.2 : 8, textTransform: "uppercase", letterSpacing: .3, color: "#6b7280", fontWeight: 850 };
  const value: React.CSSProperties = { marginTop: 2, fontSize: compact ? 9.4 : 10.3, fontWeight: 900, color: "#111827" };

  return (
    <section className="print-page report-page-break cumulative-transcript-page cumulative-transcript-classic" style={page}>
      {showWatermark && branding.reportCardWatermark && (
        <img src={branding.reportCardWatermark} alt="Watermark" style={{ position: "absolute", inset: "30% 25%", width: "50%", opacity: .035, objectFit: "contain", pointerEvents: "none" }} />
      )}

      <div style={{ position: "relative", zIndex: 1 }}>
        <header style={{ display: "grid", gridTemplateColumns: "56px 1fr auto", gap: 10, alignItems: "center", borderBottom: `3px solid ${primary}`, paddingBottom: 8 }}>
          <div style={{ width: 54, height: 54, border: "1px solid #9ca3af", display: "flex", alignItems: "center", justifyContent: "center" }}>
            {branding.logo ? <img src={branding.logo} alt="School logo" style={{ width: "100%", height: "100%", objectFit: "contain", padding: 4 }} /> : <span style={{ fontSize: 7, fontWeight: 900 }}>LOGO</span>}
          </div>
          <div>
            <div style={{ fontSize: compact ? 16 : 19, fontWeight: 950, textTransform: "uppercase", lineHeight: 1.05 }}>{safeText(branding.schoolName, "School")}</div>
            <div style={{ marginTop: 3, fontSize: compact ? 8 : 9, fontWeight: 750, color: "#4b5563" }}>{[branding.address, branding.phone, branding.email].filter(Boolean).join(" • ")}</div>
          </div>
          <div style={{ border: `1px solid ${primary}`, padding: "7px 10px", textAlign: "center", fontWeight: 950, textTransform: "uppercase", fontSize: compact ? 8 : 9 }}>
            Cumulative<br />Academic Transcript
          </div>
        </header>

        <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 6 }}>
          {[
            [labels.student, transcript.studentName],
            [labels.studentId, transcript.admissionNumber || "-"],
            [labels.gender, transcript.gender || "-"],
            [labels.className, transcript.currentClassName || "-"],
          ].map(([l, v]) => (
            <div key={l} style={{ border: "1px solid #d1d5db", padding: 6, background: "#f9fafb" }}><div style={label}>{l}</div><div style={value}>{v}</div></div>
          ))}
        </div>

        <div style={{ marginTop: 11, display: "grid", gridTemplateColumns: "repeat(5, minmax(0, 1fr))", border: "1px solid #111827" }}>
          {[
            ["Periods", transcript.totalPeriods],
            ["Subjects", transcript.totalSubjects],
            ["Cumulative Avg.", `${formatNumber(transcript.cumulativeAverage, 1)}%`],
            [labels.gpa, transcript.cumulativeGPA != null ? formatNumber(transcript.cumulativeGPA, 2) : "-"],
            ["Trend", trendLabel(transcript.overallTrend)],
          ].map(([l, v], index) => (
            <div key={l} style={{ padding: 7, textAlign: "center", borderLeft: index ? "1px solid #111827" : 0 }}><div style={label}>{l}</div><div style={{ ...value, fontSize: compact ? 10.5 : 12 }}>{v}</div></div>
          ))}
        </div>

        <div style={{ marginTop: 12, fontSize: compact ? 9 : 10, fontWeight: 950, textTransform: "uppercase", borderBottom: "1px solid #111827", paddingBottom: 4 }}>Beginning of Academic Records</div>

        {transcript.periods.map((period) => (
          <div key={`${period.academicPeriodId}-${period.snapshotId || "p"}`} style={{ marginTop: 10, breakInside: "avoid" }}>
            <div style={{ display: "flex", justifyContent: "space-between", gap: 10, fontSize: compact ? 9 : 10.2, fontWeight: 950, padding: "5px 7px", background: "#f3f4f6", border: "1px solid #111827", borderBottom: 0 }}>
              <span>{period.academicPeriodName}</span>
              <span>{period.className}</span>
            </div>
            <table style={table}>
              <thead><tr>
                <th style={{ ...th, textAlign: "left" }}>{labels.subject}</th>
                {settings.showTotal !== false && <th style={th}>{labels.total}</th>}
                {settings.showAverage !== false && <th style={th}>%</th>}
                {settings.showGrade !== false && <th style={th}>{labels.grade}</th>}
                {settings.showSubjectPosition !== false && <th style={th}>{labels.position}</th>}
                {settings.showSubjectRemarks !== false && <th style={{ ...th, textAlign: "left" }}>Remark</th>}
              </tr></thead>
              <tbody>
                {period.subjectResults.map((subject) => (
                  <tr key={`${period.academicPeriodId}-${subject.subjectId || subject.classSubjectId || subject.subjectName}`}>
                    <td style={{ ...td, fontWeight: 850 }}>{subject.subjectName}{subject.subjectCode && <div style={{ fontSize: 7.5, opacity: .75 }}>{subject.subjectCode}</div>}</td>
                    {settings.showTotal !== false && <td style={{ ...td, textAlign: "center" }}>{formatNumber(subject.total ?? subject.weightedTotal ?? subject.percentage, 1)}</td>}
                    {settings.showAverage !== false && <td style={{ ...td, textAlign: "center" }}>{formatNumber(subject.percentage, 1)}%</td>}
                    {settings.showGrade !== false && <td style={{ ...td, textAlign: "center", fontWeight: 900 }}>{subject.grade || "-"}</td>}
                    {settings.showSubjectPosition !== false && <td style={{ ...td, textAlign: "center" }}>{ordinal(subject.position)}</td>}
                    {settings.showSubjectRemarks !== false && <td style={td}>{subject.remark || "-"}</td>}
                  </tr>
                ))}
                {!period.subjectResults.length && <tr><td style={{ ...td, textAlign: "center", padding: 12 }} colSpan={6}>No subject records for this period.</td></tr>}
              </tbody>
            </table>
            {settings.showTranscriptTermBreakdown !== false && (
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", border: "1px solid #111827", borderTop: 0, fontSize: compact ? 8 : 9 }}>
                <div style={{ padding: 5 }}><strong>Term Total:</strong> {formatNumber(period.total, 1)}</div>
                <div style={{ padding: 5, borderLeft: "1px solid #d1d5db" }}><strong>Term Avg:</strong> {formatNumber(period.average, 1)}%</div>
                <div style={{ padding: 5, borderLeft: "1px solid #d1d5db" }}><strong>Term GPA:</strong> {period.gpa != null ? formatNumber(period.gpa, 2) : "-"}</div>
                <div style={{ padding: 5, borderLeft: "1px solid #d1d5db" }}><strong>Class Rank:</strong> {ordinal(period.position)}</div>
              </div>
            )}
          </div>
        ))}

        <div style={{ marginTop: 12, border: "1px solid #111827", padding: 8 }}>
          <div style={{ fontWeight: 950, textTransform: "uppercase", fontSize: compact ? 8 : 9, marginBottom: 6 }}>End of Transcript Statistics</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 6, fontSize: compact ? 8.5 : 9.5 }}>
            <div><strong>Highest Avg:</strong> {formatNumber(transcript.highestAverage, 1)}%</div>
            <div><strong>Lowest Avg:</strong> {formatNumber(transcript.lowestAverage, 1)}%</div>
            {settings.showTranscriptCumulativeAverage !== false && <div><strong>Cum Avg:</strong> {formatNumber(transcript.cumulativeAverage, 1)}%</div>}
            {settings.showTranscriptCumulativePosition !== false && <div><strong>Latest Rank:</strong> {ordinal(transcript.latestPosition)}</div>}
          </div>
        </div>

        <footer style={{ marginTop: 10, borderTop: "1px solid #111827", paddingTop: 5, display: "flex", justifyContent: "space-between", fontSize: 7.5, color: "#4b5563" }}>
          <span>{labels.footer}</span>
          {settings.showGeneratedDate !== false && <span>{labels.generated}: {formatDate(generatedAt)}</span>}
        </footer>
      </div>
    </section>
  );
}
