"use client";

import React from "react";

import type { ReportCardTemplateSetting } from "../../../../lib/db/db";
import type { ReportHeaderData } from "../engine/report-types";
import type { StudentCumulativeTranscript } from "../engine/cumulative-report-types";

type Props = {
  dataset?: {
    header?: ReportHeaderData;
    transcript?: StudentCumulativeTranscript | null;
    generatedAt?: string | number | Date | null;
  } | null;
  header?: ReportHeaderData;
  transcript?: StudentCumulativeTranscript | null;
  settings?: Partial<ReportCardTemplateSetting> | null;
  compact?: boolean;
  showWatermark?: boolean;
  pageBreakAfter?: boolean;
};

const formatNumber = (value?: number | null, decimals = 1) => {
  if (value == null || Number.isNaN(Number(value))) return "-";
  return Number(value).toFixed(decimals);
};

const formatDate = (value?: string | number | Date | null) => {
  if (!value) return "-";
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleDateString("en-GB", { year: "numeric", month: "short", day: "2-digit" });
};

const ordinal = (value?: number | null) => {
  if (!value) return "-";
  const suffixes = ["th", "st", "nd", "rd"];
  const mod100 = value % 100;
  return `${value}${suffixes[(mod100 - 20) % 10] || suffixes[mod100] || suffixes[0]}`;
};

const trendLabel = (trend?: string | null) => {
  if (trend === "up") return "Improving";
  if (trend === "down") return "Declining";
  if (trend === "stable") return "Stable";
  return "-";
};

const decisionLabel = (value?: string | null) => {
  if (!value) return "-";
  return value.charAt(0).toUpperCase() + value.slice(1);
};

const safeText = (...values: unknown[]) => {
  for (const value of values) {
    const text = String(value ?? "").trim();
    if (text) return text;
  }
  return "-";
};

function buildContext(props: Props) {
  const header = props.header || props.dataset?.header;
  const transcript = props.transcript ?? props.dataset?.transcript ?? null;
  const settings = props.settings || {};
  const branding = header?.branding || ({} as any);
  const primary = branding.primaryColor || "#111827";
  const generatedAt = props.dataset?.generatedAt || new Date();

  const labels = {
    student: settings.studentNameLabel || "Student",
    studentId: settings.admissionNumberLabel || "Student ID",
    gender: settings.genderLabel || "Gender",
    className: settings.classLabel || "Programme / Class",
    period: settings.academicPeriodLabel || "Academic Period",
    subject: settings.subjectLabel || "Course / Subject",
    total: settings.totalLabel || "Score",
    average: settings.averageLabel || "Average",
    grade: settings.gradeLabel || "Grade",
    position: settings.subjectPositionLabel || "Rank",
    classPosition: settings.classPositionLabel || "Cumulative Position",
    gpa: settings.gpaLabel || "GPA",
    generated: settings.generatedDateLabel || "Date Generated",
    footer: settings.footerText || "Official cumulative academic transcript generated by Eleeveon Schools.",
  };

  return { header, transcript, settings, branding, primary, labels, generatedAt };
}

function EmptyTranscript({ header, title, primary, compact, pageBreakAfter }: { header?: ReportHeaderData; title: string; primary: string; compact: boolean; pageBreakAfter: boolean }) {
  const branding = header?.branding || ({} as any);
  return (
    <section
      className="print-page report-page-break cumulative-transcript-page"
      style={{
        width: "210mm",
        minHeight: "297mm",
        margin: "0 auto 20px",
        padding: compact ? "9mm" : "11mm",
        boxSizing: "border-box",
        background: "#fff",
        color: "#111827",
        fontFamily: branding.fontFamily || "Arial, sans-serif",
        border: "1px solid #d1d5db",
        pageBreakAfter: pageBreakAfter ? "always" : "auto",
      }}
    >
      <div style={{ borderBottom: `3px solid ${primary}`, paddingBottom: 8, marginBottom: 16 }}>
        <div style={{ fontSize: compact ? 15 : 18, fontWeight: 950, textTransform: "uppercase" }}>{safeText(branding.schoolName, "School")}</div>
        <div style={{ fontSize: 10, fontWeight: 800, color: "#4b5563" }}>{title}</div>
      </div>
      <div style={{ border: "1px dashed #9ca3af", padding: 18, textAlign: "center", fontWeight: 800, borderRadius: 10 }}>
        Select a student with historical report snapshots to generate a cumulative academic transcript.
      </div>
    </section>
  );
}

export default function CumulativeTranscriptModern(props: Props) {
  const { header, transcript, settings, branding, primary, labels, generatedAt } = buildContext(props);
  const compact = props.compact ?? false;
  const pageBreakAfter = props.pageBreakAfter ?? true;

  if (!transcript) {
    return <EmptyTranscript header={header} title="Modern Cumulative Transcript" primary={primary} compact={compact} pageBreakAfter={pageBreakAfter} />;
  }

  const page: React.CSSProperties = { width: "210mm", minHeight: "297mm", margin: "0 auto 20px", padding: compact ? "9mm" : "11mm", boxSizing: "border-box", background: "linear-gradient(180deg,#ffffff,#f8fafc)", color: "#0f172a", fontFamily: branding.fontFamily || "Arial, sans-serif", border: "1px solid #e2e8f0", borderRadius: 18, pageBreakAfter: pageBreakAfter ? "always" : "auto", overflow: "hidden" };
  const chip: React.CSSProperties = { border: "1px solid #e2e8f0", borderRadius: 14, padding: compact ? 6 : 8, background: "rgba(255,255,255,.9)" };
  const table: React.CSSProperties = { width: "100%", borderCollapse: "separate", borderSpacing: 0, fontSize: compact ? 8.3 : 9.1, overflow: "hidden" };
  const th: React.CSSProperties = { padding: compact ? 4 : 6, background: primary, color: "#fff", textAlign: "center", fontWeight: 950, borderBottom: `1px solid ${primary}` };
  const td: React.CSSProperties = { padding: compact ? 4 : 6, borderBottom: "1px solid #e5e7eb", verticalAlign: "top" };

  return (
    <section className="print-page report-page-break cumulative-transcript-page cumulative-transcript-modern" style={page}>
      <header style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: 14, alignItems: "center" }}>
        <div>
          <div style={{ fontSize: compact ? 18 : 22, fontWeight: 950, textTransform: "uppercase", color: "#0f172a" }}>{safeText(branding.schoolName, "School")}</div>
          <div style={{ marginTop: 3, color: "#64748b", fontWeight: 750, fontSize: compact ? 8 : 9 }}>{[branding.branchName, branding.address, branding.email].filter(Boolean).join(" • ")}</div>
        </div>
        <div style={{ background: primary, color: "#fff", borderRadius: 999, padding: "8px 14px", fontSize: compact ? 8 : 9, fontWeight: 950, textTransform: "uppercase", textAlign: "center" }}>Cumulative Transcript</div>
      </header>

      <div style={{ marginTop: 12, display: "grid", gridTemplateColumns: "1.4fr repeat(4, 1fr)", gap: 7 }}>
        <div style={{ ...chip, gridRow: "span 2" }}>
          <div style={{ fontSize: 8, fontWeight: 900, color: "#64748b", textTransform: "uppercase" }}>{labels.student}</div>
          <div style={{ fontSize: compact ? 16 : 19, fontWeight: 950 }}>{transcript.studentName}</div>
          <div style={{ marginTop: 4, fontSize: compact ? 8 : 9, color: "#64748b", fontWeight: 760 }}>{labels.studentId}: {transcript.admissionNumber || "-"}</div>
        </div>
        {[["Periods", transcript.totalPeriods], ["Subjects", transcript.totalSubjects], [labels.average, `${formatNumber(transcript.cumulativeAverage, 1)}%`], [labels.gpa, transcript.cumulativeGPA != null ? formatNumber(transcript.cumulativeGPA, 2) : "-"], ["Highest", `${formatNumber(transcript.highestAverage, 1)}%`], ["Lowest", `${formatNumber(transcript.lowestAverage, 1)}%`], ["Latest Rank", ordinal(transcript.latestPosition)], ["Trend", trendLabel(transcript.overallTrend)]].map(([l, v]) => (
          <div key={String(l)} style={{ ...chip, textAlign: "center" }}><div style={{ fontSize: 7.5, fontWeight: 900, color: "#64748b", textTransform: "uppercase" }}>{l}</div><div style={{ marginTop: 2, fontSize: compact ? 11 : 13, fontWeight: 950 }}>{v}</div></div>
        ))}
      </div>

      {transcript.periods.map((period) => (
        <div key={`${period.academicPeriodId}-${period.snapshotId || "modern"}`} style={{ marginTop: 11, border: "1px solid #e2e8f0", borderRadius: 16, overflow: "hidden", background: "#fff", breakInside: "avoid" }}>
          <div style={{ display: "flex", justifyContent: "space-between", gap: 12, padding: compact ? "7px 9px" : "8px 11px", background: "#f8fafc", borderBottom: "1px solid #e2e8f0" }}>
            <div><strong>{period.academicPeriodName}</strong><div style={{ fontSize: 8, color: "#64748b" }}>{period.className}</div></div>
            <div style={{ textAlign: "right", fontSize: 8.5 }}><strong>{formatNumber(period.average, 1)}%</strong><div style={{ color: "#64748b" }}>Term Average</div></div>
          </div>
          <table style={table}>
            <thead><tr><th style={{ ...th, textAlign: "left" }}>{labels.subject}</th><th style={th}>%</th><th style={th}>{labels.grade}</th>{settings.showSubjectPosition !== false && <th style={th}>{labels.position}</th>}{settings.showSubjectRemarks !== false && <th style={{ ...th, textAlign: "left" }}>Remark</th>}</tr></thead>
            <tbody>{period.subjectResults.map((subject) => <tr key={`${period.academicPeriodId}-${subject.subjectId || subject.subjectName}`}><td style={{ ...td, fontWeight: 850 }}>{subject.subjectName}</td><td style={{ ...td, textAlign: "center" }}>{formatNumber(subject.percentage, 1)}%</td><td style={{ ...td, textAlign: "center", fontWeight: 950 }}>{subject.grade || "-"}</td>{settings.showSubjectPosition !== false && <td style={{ ...td, textAlign: "center" }}>{ordinal(subject.position)}</td>}{settings.showSubjectRemarks !== false && <td style={td}>{subject.remark || "-"}</td>}</tr>)}</tbody>
          </table>
        </div>
      ))}

      <footer style={{ marginTop: 10, display: "flex", justifyContent: "space-between", fontSize: 8, color: "#64748b", borderTop: "1px solid #e2e8f0", paddingTop: 6 }}>
        <span>{labels.footer}</span>{settings.showGeneratedDate !== false && <span>{labels.generated}: {formatDate(generatedAt)}</span>}
      </footer>
    </section>
  );
}
