"use client";

/**
 * reports/components/CumulativeTranscriptCard.tsx
 * ---------------------------------------------------------
 * ELEEVEON SCHOOLS — CUMULATIVE TRANSCRIPT TEMPLATE ROUTER
 * ---------------------------------------------------------
 *
 * This component is the cumulative-transcript equivalent of StudentReportCard.
 *
 * Purpose:
 * - receive one normalized cumulative transcript dataset
 * - resolve the selected transcript template from reportCardTemplates/settings
 * - render the selected cumulative transcript template
 * - keep the same A4/PDF-like fit-view behavior used by report cards
 * - keep app controls out of print output
 *
 * Important:
 * - This component does not compute transcript data.
 * - It only renders a normalized dataset created by the cumulative report engine.
 * - It does not reuse StudentReportCard because transcript mode is not a report-book.
 */

import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";

import {
  CUMULATIVE_TRANSCRIPT_TEMPLATE_REGISTRY,
  getCumulativeTranscriptTemplateRegistryItem,
  resolveCumulativeTranscriptTemplateComponent,
} from "../cumulative-transcript-templates";

// ======================================================
// TYPES
// ======================================================

export type CumulativeTranscriptTemplateLike = {
  id?: number;
  name?: string;
  code?: string;
  templateCode?: string;
  layoutKey?: string;
  templateKey?: string;
  reportType?: string;
  paperSize?: string;
  orientation?: "portrait" | "landscape" | string;
  density?: "compact" | "comfortable" | "spacious" | string;
  active?: boolean;
  [key: string]: any;
};

export type CumulativeTranscriptSettingsLike = {
  templateId?: number | null;
  templateCode?: string;
  layoutKey?: string;
  templateKey?: string;
  templateName?: string;
  reportType?: string;

  paperSize?: string;
  orientation?: "portrait" | "landscape" | string;
  density?: "compact" | "comfortable" | "spacious" | string;

  showStudentPhoto?: boolean;
  showAdmissionNumber?: boolean;
  showGender?: boolean;
  showClass?: boolean;
  showAcademicStructure?: boolean;
  showAcademicPeriod?: boolean;
  showBranch?: boolean;

  showTranscriptTermBreakdown?: boolean;
  showTranscriptYearAverage?: boolean;
  showTranscriptCumulativeAverage?: boolean;
  showTranscriptCumulativePosition?: boolean;
  showTranscriptGPAProgression?: boolean;
  showTranscriptFinalRecommendation?: boolean;
  showGeneratedDate?: boolean;
  showLogo?: boolean;
  showWatermark?: boolean;

  studentNameLabel?: string;
  admissionNumberLabel?: string;
  genderLabel?: string;
  classLabel?: string;
  academicStructureLabel?: string;
  academicPeriodLabel?: string;
  subjectLabel?: string;
  totalLabel?: string;
  averageLabel?: string;
  gradeLabel?: string;
  classPositionLabel?: string;
  gpaLabel?: string;
  generatedDateLabel?: string;
  footerText?: string;

  [key: string]: any;
};

export type CumulativeTranscriptCardProps = {
  dataset?: any;
  template?: CumulativeTranscriptTemplateLike | null;
  settings?: CumulativeTranscriptSettingsLike | null;
  compact?: boolean;
  showWatermark?: boolean;
  pageBreakAfter?: boolean;
  mobilePreview?: boolean;
  className?: string;
};

// ======================================================
// DEFAULT SETTINGS
// ======================================================

const DEFAULT_CUMULATIVE_TRANSCRIPT_SETTINGS: CumulativeTranscriptSettingsLike = {
  reportType: "cumulative_transcript",
  templateCode: "cumulative_transcript_classic",
  layoutKey: "cumulative_transcript_classic",
  templateName: "Cumulative Transcript Classic",
  paperSize: "A4",
  orientation: "portrait",
  density: "compact",

  showAdmissionNumber: true,
  showGender: true,
  showClass: true,
  showAcademicStructure: true,
  showAcademicPeriod: true,
  showBranch: true,
  showTranscriptTermBreakdown: true,
  showTranscriptYearAverage: true,
  showTranscriptCumulativeAverage: true,
  showTranscriptCumulativePosition: true,
  showTranscriptGPAProgression: true,
  showTranscriptFinalRecommendation: true,
  showGeneratedDate: true,
  showLogo: true,
  showWatermark: false,

  studentNameLabel: "Student",
  admissionNumberLabel: "Student ID",
  genderLabel: "Gender",
  classLabel: "Programme / Class",
  academicStructureLabel: "Academic Structure",
  academicPeriodLabel: "Academic Period",
  subjectLabel: "Course / Subject",
  totalLabel: "Total",
  averageLabel: "Average",
  gradeLabel: "Grade",
  classPositionLabel: "Position",
  gpaLabel: "GPA",
  generatedDateLabel: "Date Generated",
  footerText: "Official cumulative academic transcript generated by Eleeveon Schools.",
};

// ======================================================
// HELPERS
// ======================================================

function firstText(...values: unknown[]) {
  for (const value of values) {
    const text = String(value ?? "").trim();
    if (text) return text;
  }
  return "";
}

function templateCodeOf(
  template?: CumulativeTranscriptTemplateLike | null,
  settings?: CumulativeTranscriptSettingsLike | null
) {
  return firstText(
    template?.code,
    template?.templateCode,
    template?.layoutKey,
    template?.templateKey,
    settings?.templateCode,
    settings?.layoutKey,
    settings?.templateKey,
    DEFAULT_CUMULATIVE_TRANSCRIPT_SETTINGS.templateCode
  );
}

function mergeTranscriptSettings(args: {
  template?: CumulativeTranscriptTemplateLike | null;
  settings?: CumulativeTranscriptSettingsLike | null;
  compact?: boolean;
}) {
  const registryItem = getCumulativeTranscriptTemplateRegistryItem(
    templateCodeOf(args.template, args.settings)
  );

  const selectedCode =
    registryItem?.code ||
    args.template?.code ||
    args.template?.templateCode ||
    args.template?.layoutKey ||
    args.settings?.templateCode ||
    DEFAULT_CUMULATIVE_TRANSCRIPT_SETTINGS.templateCode ||
    "cumulative_transcript_classic";

  return {
    ...DEFAULT_CUMULATIVE_TRANSCRIPT_SETTINGS,
    ...(args.settings || {}),
    reportType: "cumulative_transcript",
    templateName:
      args.template?.name ||
      args.settings?.templateName ||
      registryItem?.name ||
      DEFAULT_CUMULATIVE_TRANSCRIPT_SETTINGS.templateName,
    templateCode: selectedCode,
    layoutKey: args.template?.layoutKey || args.settings?.layoutKey || selectedCode,
    templateKey: args.template?.templateKey || args.settings?.templateKey || selectedCode,
    paperSize: args.template?.paperSize || args.settings?.paperSize || "A4",
    orientation: args.template?.orientation || args.settings?.orientation || "portrait",
    density:
      args.settings?.density ||
      args.template?.density ||
      (args.compact ? "compact" : DEFAULT_CUMULATIVE_TRANSCRIPT_SETTINGS.density),
  };
}

function emptyTranscriptMessage(dataset: any) {
  if (!dataset) return "No cumulative transcript dataset was provided.";
  return "No cumulative transcript records are available for the selected student or filters.";
}

function datasetStudentTitle(dataset: any) {
  return firstText(
    dataset?.student?.studentName,
    dataset?.student?.fullName,
    dataset?.studentName,
    dataset?.summary?.studentName,
    "Cumulative Transcript"
  );
}

function datasetSubtitle(dataset: any) {
  return firstText(
    dataset?.student?.admissionNumber,
    dataset?.student?.studentId,
    dataset?.summary?.programmeName,
    dataset?.summary?.className,
    dataset?.branding?.schoolName,
    dataset?.header?.branding?.schoolName,
    "Academic Records"
  );
}

// ======================================================
// COMPONENT
// ======================================================

export default function CumulativeTranscriptCard({
  dataset,
  template,
  settings,
  compact = false,
  showWatermark = true,
  pageBreakAfter = true,
  mobilePreview = true,
  className = "",
}: CumulativeTranscriptCardProps) {
  const [expanded, setExpanded] = useState(false);
  const [fitScale, setFitScale] = useState(1);
  const [zoomScale, setZoomScale] = useState(1);
  const [zoomMenuOpen, setZoomMenuOpen] = useState(false);
  const previewFrameRef = useRef<HTMLDivElement | null>(null);
  const holdTimerRef = useRef<number | null>(null);
  const holdIntervalRef = useRef<number | null>(null);

  const resolvedSettings = useMemo(
    () => mergeTranscriptSettings({ template, settings, compact }),
    [template, settings, compact]
  );

  const selectedCode = templateCodeOf(template, resolvedSettings);
  const TemplateComponent = useMemo(
    () => resolveCumulativeTranscriptTemplateComponent(selectedCode),
    [selectedCode]
  );

  const previewScale = expanded ? zoomScale : fitScale;
  const displayZoomPercent = Math.round(previewScale * 100);
  const ZOOM_STEP = 1.01;

  const applyZoomStep = useCallback(
    (direction: "in" | "out") => {
      setZoomScale((prev) => {
        const baseScale = expanded ? prev : fitScale;
        const nextScale = direction === "in" ? baseScale * ZOOM_STEP : baseScale / ZOOM_STEP;
        return Math.min(2, Math.max(0.25, Number(nextScale.toFixed(4))));
      });
      setExpanded(true);
    },
    [expanded, fitScale]
  );

  const stopZoomHold = useCallback(() => {
    if (holdTimerRef.current != null) {
      window.clearTimeout(holdTimerRef.current);
      holdTimerRef.current = null;
    }

    if (holdIntervalRef.current != null) {
      window.clearInterval(holdIntervalRef.current);
      holdIntervalRef.current = null;
    }
  }, []);

  const startZoomHold = useCallback(
    (direction: "in" | "out") => {
      stopZoomHold();
      applyZoomStep(direction);

      holdTimerRef.current = window.setTimeout(() => {
        holdIntervalRef.current = window.setInterval(() => {
          applyZoomStep(direction);
        }, 55);
      }, 260);
    },
    [applyZoomStep, stopZoomHold]
  );

  const fitToScreen = () => {
    stopZoomHold();
    setExpanded(false);
    setZoomScale(1);
    setZoomMenuOpen(false);
  };

  const selectZoomPercent = (percent: number) => {
    stopZoomHold();
    setExpanded(true);
    setZoomScale(Number((percent / 100).toFixed(4)));
    setZoomMenuOpen(false);
  };

  useEffect(() => {
    if (!mobilePreview) return;

    const A4_WIDTH_PX = 793.7008;
    const A4_HEIGHT_PX = 1122.5197;
    const SAFE_GAP = 8;

    const updateScale = () => {
      const frame = previewFrameRef.current;
      if (!frame) return;

      const rect = frame.getBoundingClientRect();
      const availableWidth = Math.max(120, rect.width - SAFE_GAP);
      const availableHeight = Math.max(180, window.innerHeight - rect.top - SAFE_GAP);
      const widthScale = availableWidth / A4_WIDTH_PX;
      const heightScale = availableHeight / A4_HEIGHT_PX;
      const nextScale = Math.min(1, widthScale, heightScale);

      setFitScale(Number(nextScale.toFixed(4)));
    };

    updateScale();

    const observer = new ResizeObserver(updateScale);
    if (previewFrameRef.current) observer.observe(previewFrameRef.current);

    window.addEventListener("resize", updateScale);
    window.addEventListener("orientationchange", updateScale);

    return () => {
      observer.disconnect();
      window.removeEventListener("resize", updateScale);
      window.removeEventListener("orientationchange", updateScale);
    };
  }, [mobilePreview]);

  useEffect(() => {
    return () => stopZoomHold();
  }, [stopZoomHold]);

  const reportPage = dataset ? (
    <TemplateComponent
      dataset={dataset}
      template={template || null}
      settings={resolvedSettings}
      compact={compact}
      showWatermark={showWatermark}
      pageBreakAfter={pageBreakAfter}
      mobilePreview={false}
    />
  ) : (
    <section className="print-page report-page-break cumulative-transcript-empty-page ctc-a4-page">
      <div className="ctc-empty-card">{emptyTranscriptMessage(dataset)}</div>
    </section>
  );

  if (!mobilePreview) {
    return (
      <div className={className}>
        <style>{css}</style>
        {reportPage}
      </div>
    );
  }

  return (
    <div className={`ctc-preview-shell ${expanded ? "expanded" : ""} ${className}`}>
      <style>{css}</style>

      <div className="ctc-mobile-toolbar report-no-print">
        <div>
          <strong>{datasetStudentTitle(dataset)}</strong>
          <span>{datasetSubtitle(dataset)}</span>
        </div>

        <div className="ctc-zoom-controls" aria-label="Cumulative transcript zoom controls">
          <button
            type="button"
            className="ctc-zoom-icon-button"
            onClick={() => applyZoomStep("out")}
            onPointerDown={() => startZoomHold("out")}
            onPointerUp={stopZoomHold}
            onPointerCancel={stopZoomHold}
            onPointerLeave={stopZoomHold}
            aria-label="Zoom out"
            title="Click or hold to zoom out"
          >
            −
          </button>

          <button
            type="button"
            className="ctc-zoom-fit-button"
            onClick={fitToScreen}
            aria-label="Fit to screen"
            title="Fit to screen"
          >
            Fit
          </button>

          <div className="ctc-zoom-menu-wrap">
            <button
              type="button"
              className="ctc-zoom-percent-button"
              onClick={() => setZoomMenuOpen((prev) => !prev)}
              aria-label="Choose zoom percentage"
              aria-expanded={zoomMenuOpen}
              title="Choose zoom percentage"
            >
              <span>{displayZoomPercent}%</span>
              <span className="ctc-zoom-caret">▾</span>
            </button>

            {zoomMenuOpen && (
              <div className="ctc-zoom-menu" role="menu">
                {[30, 40, 50, 60, 70, 80, 90, 100].map((percent) => (
                  <button
                    key={percent}
                    type="button"
                    role="menuitem"
                    onClick={() => selectZoomPercent(percent)}
                    className={`ctc-zoom-menu-item ${Math.round(previewScale * 100) === percent ? "active" : ""}`}
                  >
                    {percent}%
                  </button>
                ))}
              </div>
            )}
          </div>

          <button
            type="button"
            className="ctc-zoom-icon-button"
            onClick={() => applyZoomStep("in")}
            onPointerDown={() => startZoomHold("in")}
            onPointerUp={stopZoomHold}
            onPointerCancel={stopZoomHold}
            onPointerLeave={stopZoomHold}
            aria-label="Zoom in"
            title="Click or hold to zoom in"
          >
            +
          </button>
        </div>
      </div>

      <div
        ref={previewFrameRef}
        className="ctc-preview-scroll report-screen-scroll"
        style={{ "--ctc-preview-scale": previewScale } as React.CSSProperties}
      >
        <div className="ctc-preview-center">
          <div className="ctc-preview-scale">{reportPage}</div>
        </div>
      </div>
    </div>
  );
}

// ======================================================
// CSS
// ======================================================

const css = `
.ctc-empty-card {
  margin: 24px auto;
  padding: 20px;
  border: 1px dashed #cbd5e1;
  border-radius: 16px;
  background: #fff;
  color: #0f172a;
  font-size: 13px;
  font-weight: 800;
  text-align: center;
}

.ctc-preview-shell {
  --a4-width-px: 793.7008;
  --a4-height-px: 1122.5197;
  width: 100%;
  max-width: 100%;
  min-width: 0;
  overflow: hidden;
  border-radius: 24px;
}

.ctc-mobile-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  width: 100%;
  box-sizing: border-box;
  margin: 0 0 8px;
  padding: 10px;
  border-radius: 18px;
  background: var(--surface, #fff);
  border: 1px solid rgba(148,163,184,.22);
  box-shadow: 0 10px 24px rgba(15,23,42,.06);
}

.ctc-mobile-toolbar div {
  min-width: 0;
}

.ctc-mobile-toolbar strong,
.ctc-mobile-toolbar span {
  display: block;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.ctc-mobile-toolbar strong {
  font-size: 13px;
  font-weight: 950;
  color: var(--text, #0f172a);
}

.ctc-mobile-toolbar span {
  margin-top: 2px;
  color: var(--muted, #64748b);
  font-size: 11px;
  font-weight: 750;
}

.ctc-zoom-controls {
  flex: 0 0 auto;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 4px;
  border-radius: 999px;
  background: color-mix(in srgb, var(--muted, #64748b) 10%, transparent);
  border: 1px solid rgba(148,163,184,.18);
}

.ctc-zoom-controls button {
  appearance: none;
  -webkit-appearance: none;
  border: 0;
  cursor: pointer;
  font-family: inherit;
}

.ctc-zoom-icon-button,
.ctc-zoom-fit-button,
.ctc-zoom-percent-button {
  height: 32px;
  min-height: 32px;
  border-radius: 999px;
  background: var(--primary-color, #2563eb);
  color: #fff;
  font-weight: 950;
  line-height: 1;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  white-space: nowrap;
  box-shadow: 0 6px 14px rgba(15,23,42,.12);
}

.ctc-zoom-icon-button {
  width: 32px;
  min-width: 32px;
  padding: 0;
  font-size: 18px;
}

.ctc-zoom-fit-button {
  min-width: 42px;
  padding: 0 12px;
  font-size: 12px;
}

.ctc-zoom-menu-wrap {
  position: relative;
  display: inline-flex;
  flex: 0 0 auto;
}

.ctc-zoom-percent-button {
  min-width: 68px;
  padding: 0 10px;
  font-size: 12px;
  gap: 5px;
  font-variant-numeric: tabular-nums;
}

.ctc-zoom-caret {
  font-size: 9px;
  line-height: 1;
  opacity: .9;
  transform: translateY(1px);
}

.ctc-zoom-menu {
  position: absolute;
  right: 0;
  top: calc(100% + 8px);
  z-index: 40;
  width: 114px;
  max-height: 252px;
  overflow-y: auto;
  overflow-x: hidden;
  display: grid;
  grid-template-columns: 1fr;
  gap: 4px;
  padding: 7px;
  border-radius: 16px;
  background: var(--surface, #fff);
  border: 1px solid rgba(148,163,184,.34);
  box-shadow: 0 20px 46px rgba(15,23,42,.20);
  box-sizing: border-box;
}

.ctc-zoom-menu-item {
  width: 100%;
  min-width: 0;
  height: 32px;
  min-height: 32px;
  padding: 0 10px;
  border-radius: 11px;
  background: transparent;
  color: var(--text, #0f172a);
  box-shadow: none;
  font-size: 12px;
  font-weight: 900;
  font-variant-numeric: tabular-nums;
  display: flex !important;
  align-items: center;
  justify-content: center;
  white-space: nowrap;
  box-sizing: border-box;
}

.ctc-zoom-menu-item:hover {
  background: color-mix(in srgb, var(--primary-color, #2563eb) 10%, transparent);
}

.ctc-zoom-menu-item.active {
  background: var(--primary-color, #2563eb);
  color: #fff;
}

.ctc-preview-scroll {
  --ctc-preview-scale: 1;
  width: 100%;
  max-width: 100%;
  min-width: 0;
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
  padding: 4px;
  border-radius: 22px;
  background: rgba(148,163,184,.10);
  border: 1px solid rgba(148,163,184,.18);
  box-sizing: border-box;
}

.ctc-preview-center {
  width: 100%;
  height: calc(297mm * var(--ctc-preview-scale));
  min-height: calc(297mm * var(--ctc-preview-scale));
  display: flex;
  justify-content: center;
  align-items: flex-start;
  overflow: hidden;
}

.ctc-preview-scale {
  width: 210mm;
  height: 297mm;
  min-width: 210mm;
  min-height: 297mm;
  transform: scale(var(--ctc-preview-scale));
  transform-origin: top center;
  flex: 0 0 auto;
}

.ctc-a4-page,
.cumulative-transcript-page,
.cumulative-transcript-empty-page {
  width: 210mm !important;
  min-width: 210mm !important;
  max-width: 210mm !important;
  min-height: 297mm !important;
  box-sizing: border-box !important;
}

.ctc-preview-shell:not(.expanded) .ctc-preview-scroll {
  overflow: hidden;
}

.ctc-preview-shell.expanded .ctc-preview-scroll {
  overflow: auto;
  max-height: none;
}

.ctc-preview-shell.expanded .ctc-preview-center {
  width: max(100%, calc(210mm * var(--ctc-preview-scale)));
  height: calc(297mm * var(--ctc-preview-scale));
  min-height: calc(297mm * var(--ctc-preview-scale));
  display: flex;
  justify-content: center;
  align-items: flex-start;
  overflow: visible;
  margin: 0 auto;
}

@media screen and (max-width: 380px) {
  .ctc-mobile-toolbar {
    gap: 6px;
    padding: 8px;
  }

  .ctc-mobile-toolbar strong {
    font-size: 12px;
  }

  .ctc-mobile-toolbar span {
    font-size: 10px;
  }

  .ctc-zoom-controls {
    gap: 3px;
    padding: 3px;
  }

  .ctc-zoom-icon-button {
    width: 29px;
    min-width: 29px;
    height: 29px;
    min-height: 29px;
    font-size: 16px;
  }

  .ctc-zoom-fit-button {
    min-width: 36px;
    height: 29px;
    min-height: 29px;
    padding: 0 8px;
    font-size: 10px;
  }

  .ctc-zoom-percent-button {
    min-width: 62px;
    height: 29px;
    min-height: 29px;
    padding: 0 8px;
    font-size: 10px;
  }
}

@media print {
  .ctc-preview-shell,
  .ctc-preview-scroll,
  .ctc-preview-center,
  .ctc-preview-scale {
    display: contents !important;
    transform: none !important;
    width: auto !important;
    height: auto !important;
    min-width: 0 !important;
    min-height: 0 !important;
    overflow: visible !important;
    padding: 0 !important;
    margin: 0 !important;
    border: 0 !important;
    background: transparent !important;
    box-shadow: none !important;
  }

  .ctc-mobile-toolbar,
  .report-no-print {
    display: none !important;
    visibility: hidden !important;
  }

  .ctc-a4-page,
  .cumulative-transcript-page,
  .cumulative-transcript-empty-page {
    width: 210mm !important;
    min-width: 210mm !important;
    max-width: 210mm !important;
    min-height: 297mm !important;
    transform: none !important;
    margin: 0 auto !important;
    box-shadow: none !important;
    page-break-inside: avoid !important;
    break-inside: avoid !important;
  }

  table,
  tr,
  td,
  th {
    page-break-inside: avoid !important;
    break-inside: avoid !important;
  }
}
`;
