"use client";

/**
 * reports/components/StudentProgressionTimeline.tsx
 * ---------------------------------------------------------
 * STUDENT PROGRESSION TIMELINE
 * ---------------------------------------------------------
 *
 * Visualizes a learner's academic journey from StudentPromotion
 * records generated by the cumulative report engine.
 *
 * Mobile enhancement:
 * - Original A4 print design is preserved.
 * - Mobile preview is wrapped safely.
 * - Cards are readable on small screens.
 * - Table overflow is isolated inside the component.
 * - No dashboard horizontal overflow.
 */

import React, { useMemo, useState } from "react";

import ReportHeader from "./ReportHeader";

import type { StudentProgressionStep } from "../engine/cumulative-report-types";
import type { ReportHeaderData } from "../engine/report-types";

// ======================================================
// PROPS
// ======================================================

type Props = {
  steps?: StudentProgressionStep[];
  header: ReportHeaderData;
  studentName?: string;
  compact?: boolean;
  pageBreakAfter?: boolean;
  mobilePreview?: boolean;
};

// ======================================================
// HELPERS
// ======================================================

const formatNumber = (value?: number, decimals = 1) => {
  if (value == null || Number.isNaN(value)) return "0";
  return Number(value).toFixed(decimals);
};

const decisionLabel = (value?: string) => {
  if (!value) return "-";
  return value.charAt(0).toUpperCase() + value.slice(1);
};

const decisionTone = (value?: string) => {
  if (value === "promote") return "#16a34a";
  if (value === "repeat") return "#dc2626";
  if (value === "graduate") return "#2563eb";
  return "#111827";
};

const decisionBg = (value?: string) => {
  if (value === "promote") return "rgba(22,163,74,0.10)";
  if (value === "repeat") return "rgba(220,38,38,0.10)";
  if (value === "graduate") return "rgba(37,99,235,0.10)";
  return "rgba(17,24,39,0.06)";
};

const stepKey = (step: StudentProgressionStep, index: number) => {
  return String(step.id ?? step.snapshotId ?? index);
};

// ======================================================
// COMPONENT
// ======================================================

export default function StudentProgressionTimeline({
  steps = [],
  header,
  studentName,
  compact = false,
  pageBreakAfter = true,
  mobilePreview = true,
}: Props) {
  const branding = header.branding;
  const primary = branding.primaryColor || "var(--primary-color)";

  const [previewExpanded, setPreviewExpanded] = useState(false);
  const [openCards, setOpenCards] = useState<Record<string, boolean>>({});

  const promoted = useMemo(
    () => steps.filter((step) => step.finalDecision === "promote").length,
    [steps],
  );

  const repeated = useMemo(
    () => steps.filter((step) => step.finalDecision === "repeat").length,
    [steps],
  );

  const graduated = useMemo(
    () => steps.filter((step) => step.finalDecision === "graduate").length,
    [steps],
  );

  const toggleCard = (key: string) => {
    setOpenCards((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const page: React.CSSProperties = {
    width: "210mm",
    minHeight: "297mm",
    margin: "0 auto 20px",
    padding: compact ? "9mm" : "11mm",
    boxSizing: "border-box",
    background: "#fff",
    color: "#111",
    fontFamily: branding.fontFamily || "Arial, sans-serif",
    border: "1px solid #e5e5e5",
    position: "relative",
    overflow: "hidden",
    pageBreakAfter: pageBreakAfter ? "always" : "auto",
  };

  const table: React.CSSProperties = {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: compact ? 8.5 : 9.5,
  };

  const th: React.CSSProperties = {
    border: "1px solid #222",
    padding: compact ? 3 : 5,
    background: primary,
    color: "#fff",
    textAlign: "center",
    fontWeight: 800,
    lineHeight: 1.15,
    whiteSpace: "nowrap",
  };

  const td: React.CSSProperties = {
    border: "1px solid #222",
    padding: compact ? 3 : 5,
    verticalAlign: "middle",
    lineHeight: 1.2,
  };

  const summaryCard: React.CSSProperties = {
    border: "1px solid #ddd",
    borderRadius: 12,
    padding: compact ? 8 : 10,
    background: "#fafafa",
  };

  const reportPage = (
    <section
      className="print-page report-page-break student-progression-timeline-page spt-a4-page"
      style={page}
    >
      <ReportHeader
        header={header}
        title="Student Progression Timeline"
        subtitle={
          studentName
            ? `${studentName} • ${steps.length} Progression Records`
            : `${steps.length} Progression Records`
        }
        orientation="portrait"
        compact={compact}
      />

      <div className="spt-summary-print-grid">
        <div style={summaryCard}>
          <div className="spt-summary-label">Records</div>
          <div className="spt-summary-value" style={{ color: primary }}>
            {steps.length}
          </div>
        </div>

        <div style={summaryCard}>
          <div className="spt-summary-label">Promoted</div>
          <div className="spt-summary-value" style={{ color: "#16a34a" }}>
            {promoted}
          </div>
        </div>

        <div style={summaryCard}>
          <div className="spt-summary-label">Repeated</div>
          <div className="spt-summary-value" style={{ color: "#dc2626" }}>
            {repeated}
          </div>
        </div>

        <div style={summaryCard}>
          <div className="spt-summary-label">Graduated</div>
          <div className="spt-summary-value" style={{ color: "#2563eb" }}>
            {graduated}
          </div>
        </div>
      </div>

      <div className="spt-print-timeline" style={{ borderLeftColor: primary }}>
        {steps.map((step, index) => {
          const key = stepKey(step, index);
          const isOpen = openCards[key];

          return (
            <div
              key={key}
              className="spt-print-card"
              style={{ background: decisionBg(step.finalDecision) }}
            >
              <div
                className="spt-print-dot"
                style={{ background: decisionTone(step.finalDecision) }}
              />

              <button
                type="button"
                className="spt-print-card-head report-no-print"
                onClick={() => toggleCard(key)}
              >
                <span>View Details</span>
              </button>

              <div className="spt-card-layout">
                <div>
                  <div className="spt-title">
                    {index + 1}. {step.fromClassName || "Class"} →{" "}
                    {step.toClassName || decisionLabel(step.finalDecision)}
                  </div>

                  <div className="spt-period-line">
                    {step.fromAcademicPeriodName ||
                      step.fromAcademicStructureName ||
                      "-"}
                    {" → "}
                    {step.toAcademicPeriodName ||
                      step.toAcademicStructureName ||
                      "-"}
                  </div>

                  {step.note && (
                    <div className={`spt-note ${isOpen ? "open" : ""}`}>
                      {step.note}
                    </div>
                  )}
                </div>

                <div
                  className="spt-decision-pill"
                  style={{
                    borderColor: decisionTone(step.finalDecision),
                    color: decisionTone(step.finalDecision),
                  }}
                >
                  {decisionLabel(step.finalDecision)}
                </div>
              </div>

              <div className="spt-mini-grid">
                <div>
                  <strong>Average:</strong>{" "}
                  {step.average != null
                    ? `${formatNumber(step.average, 1)}%`
                    : "-"}
                </div>

                <div>
                  <strong>Recommended:</strong>{" "}
                  {decisionLabel(step.recommendation)}
                </div>

                <div>
                  <strong>Snapshot:</strong> {step.snapshotId || "-"}
                </div>
              </div>
            </div>
          );
        })}

        {!steps.length && (
          <div className="spt-empty-box">
            No progression records found for this student.
          </div>
        )}
      </div>

      <div className="spt-table-wrap">
        <table style={table}>
          <thead>
            <tr>
              <th style={th}>#</th>
              <th style={th}>From Class</th>
              <th style={th}>To Class</th>
              <th style={th}>From Period</th>
              <th style={th}>To Period</th>
              <th style={th}>Average</th>
              <th style={th}>Recommendation</th>
              <th style={th}>Final Decision</th>
            </tr>
          </thead>

          <tbody>
            {steps.map((step, index) => (
              <tr key={`${stepKey(step, index)}-table`}>
                <td style={{ ...td, textAlign: "center" }}>{index + 1}</td>
                <td style={td}>{step.fromClassName || "-"}</td>
                <td style={td}>{step.toClassName || "-"}</td>
                <td style={td}>{step.fromAcademicPeriodName || "-"}</td>
                <td style={td}>{step.toAcademicPeriodName || "-"}</td>
                <td style={{ ...td, textAlign: "center", fontWeight: 800 }}>
                  {step.average != null
                    ? `${formatNumber(step.average, 1)}%`
                    : "-"}
                </td>
                <td style={{ ...td, textAlign: "center" }}>
                  {decisionLabel(step.recommendation)}
                </td>
                <td
                  style={{
                    ...td,
                    textAlign: "center",
                    fontWeight: 900,
                    color: decisionTone(step.finalDecision),
                  }}
                >
                  {decisionLabel(step.finalDecision)}
                </td>
              </tr>
            ))}

            {!steps.length && (
              <tr>
                <td
                  style={{ ...td, textAlign: "center", padding: 14 }}
                  colSpan={8}
                >
                  No progression records found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <div className="spt-footer" style={{ borderTopColor: primary }}>
        <span>
          Official progression timeline generated for {branding.schoolName}
        </span>
        <span>Powered by Eleeveon School Management System</span>
      </div>
    </section>
  );

  if (!mobilePreview) {
    return (
      <div className="spt-shell">
        <style>{css}</style>
        {reportPage}
      </div>
    );
  }

  return (
    <div className={`spt-shell ${previewExpanded ? "expanded" : ""}`}>
      <style>{css}</style>

      <div className="spt-toolbar report-no-print">
        <div>
          <strong>{studentName || "Progression Timeline"}</strong>
          <span>
            {steps.length} records · {promoted} promoted · {repeated} repeated
          </span>
        </div>

        <button
          type="button"
          onClick={() => setPreviewExpanded((prev) => !prev)}
        >
          {previewExpanded ? "Fit Preview" : "Expand"}
        </button>
      </div>

      <div className="spt-preview-scroll report-screen-scroll">
        <div className="spt-preview-scale">{reportPage}</div>
      </div>
    </div>
  );
}

// ======================================================
// CSS
// ======================================================

const css = `
.spt-shell {
  width: 100%;
  max-width: 100%;
  min-width: 0;
  overflow: hidden;
}

.spt-toolbar {
  display: none;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  margin-bottom: 8px;
  padding: 10px;
  border-radius: 18px;
  background: var(--surface, #fff);
  border: 1px solid rgba(148,163,184,.22);
  box-shadow: 0 10px 24px rgba(15,23,42,.06);
}

.spt-toolbar div {
  min-width: 0;
}

.spt-toolbar strong,
.spt-toolbar span {
  display: block;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.spt-toolbar strong {
  font-size: 13px;
  font-weight: 950;
  color: var(--text, #0f172a);
}

.spt-toolbar span {
  margin-top: 2px;
  color: var(--muted, #64748b);
  font-size: 11px;
  font-weight: 750;
}

.spt-toolbar button {
  flex: 0 0 auto;
  min-height: 34px;
  border: 0;
  border-radius: 999px;
  padding: 0 12px;
  background: var(--primary-color, #2563eb);
  color: #fff;
  font-size: 12px;
  font-weight: 950;
  cursor: pointer;
}

.spt-preview-scroll {
  width: 100%;
  max-width: 100%;
  min-width: 0;
  overflow-x: auto;
  overflow-y: visible;
  -webkit-overflow-scrolling: touch;
  padding: 8px;
  border-radius: 22px;
  background: rgba(148,163,184,.08);
  border: 1px solid rgba(148,163,184,.18);
}

.spt-preview-scale {
  width: max-content;
  min-width: 100%;
  transform-origin: top left;
}

.spt-summary-print-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 6px;
  margin-bottom: 12px;
}

.spt-summary-print-grid > div {
  min-width: 0;
  overflow: hidden;
}

.spt-summary-label {
  display: block;
  max-width: 100%;
  font-size: 8px;
  line-height: 1.15;
  opacity: 0.72;
  font-weight: 900;
  white-space: normal;
  overflow-wrap: anywhere;
  word-break: break-word;
}

.spt-summary-value {
  margin-top: 3px;
  font-size: 18px;
  line-height: 1;
  font-weight: 900;
}

.spt-print-timeline {
  border-left: 4px solid;
  padding-left: 14px;
  display: grid;
  gap: 10px;
  margin-bottom: 14px;
}

.spt-print-card {
  position: relative;
  border: 1px solid #ddd;
  border-radius: 14px;
  padding: 10px;
  break-inside: avoid;
}

.spt-print-dot {
  position: absolute;
  left: -25px;
  top: 14px;
  width: 18px;
  height: 18px;
  border-radius: 999px;
  border: 3px solid #fff;
  box-shadow: 0 0 0 1px #ddd;
}

.spt-print-card-head {
  display: none;
}

.spt-card-layout {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 10px;
  align-items: start;
}

.spt-title {
  font-size: 11.5px;
  font-weight: 900;
  overflow-wrap: anywhere;
}

.spt-period-line {
  margin-top: 4px;
  font-size: 9.5px;
  opacity: 0.78;
  font-weight: 650;
  overflow-wrap: anywhere;
}

.spt-note {
  margin-top: 6px;
  font-size: 9.5px;
  line-height: 1.35;
  overflow-wrap: anywhere;
}

.spt-decision-pill {
  min-width: 90px;
  text-align: center;
  border-radius: 999px;
  padding: 6px 10px;
  background: #fff;
  border: 1px solid;
  font-weight: 900;
  font-size: 9.5px;
}

.spt-mini-grid {
  margin-top: 8px;
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 6px;
  font-size: 9px;
}

.spt-mini-grid div {
  min-width: 0;
  overflow-wrap: anywhere;
}

.spt-empty-box {
  padding: 20px;
  border: 1px dashed #bbb;
  border-radius: 12px;
  text-align: center;
  font-weight: 700;
}

.spt-table-wrap {
  width: 100%;
  max-width: 100%;
  overflow-x: auto;
}

.spt-footer {
  margin-top: 10px;
  border-top: 2px solid;
  padding-top: 5px;
  display: flex;
  justify-content: space-between;
  gap: 10px;
  font-size: 8.5px;
  color: #555;
}

@media screen and (max-width: 720px) {
  .spt-summary-print-grid {
    gap: 4px;
  }

  .spt-summary-print-grid > div {
    padding: 6px !important;
    border-radius: 9px !important;
  }

  .spt-summary-label {
    font-size: 6.8px;
    letter-spacing: -0.15px;
  }

  .spt-summary-value {
    font-size: 14px;
  }

  .spt-toolbar {
    display: flex;
  }

  .spt-shell:not(.expanded) .spt-preview-scroll {
    overflow: hidden;
    max-height: 82vh;
  }

  .spt-shell:not(.expanded) .spt-preview-scale {
    width: 210mm;
    transform: scale(calc((100vw - 28px) / 793.7008));
    transform-origin: top left;
  }

  .spt-shell:not(.expanded) .spt-preview-scroll::after {
    content: "";
    display: block;
    height: calc(1122.5197px * ((100vw - 28px) / 793.7008));
  }

  .spt-shell.expanded .spt-preview-scroll {
    overflow-x: auto;
    max-height: none;
  }

  .spt-shell.expanded .spt-preview-scale {
    transform: none;
  }

  .spt-print-card-head {
    display: inline-flex;
    margin-bottom: 8px;
    border: 0;
    border-radius: 999px;
    padding: 5px 9px;
    background: rgba(255,255,255,.72);
    color: #111827;
    font-size: 9px;
    font-weight: 900;
  }

  .spt-card-layout {
    grid-template-columns: minmax(0, 1fr);
  }

  .spt-decision-pill {
    width: fit-content;
    min-width: 0;
  }

  .spt-note:not(.open) {
    display: none;
  }

  .spt-mini-grid {
    grid-template-columns: minmax(0, 1fr);
  }
}

@media print {
  .spt-shell,
  .spt-preview-scroll,
  .spt-preview-scale {
    display: contents !important;
    transform: none !important;
    overflow: visible !important;
    padding: 0 !important;
    border: 0 !important;
    background: transparent !important;
  }

  .spt-toolbar,
  .spt-print-card-head {
    display: none !important;
  }

  .spt-note {
    display: block !important;
  }
}
`;
