"use client";

/**
 * app/branch-admin/modules/reports/StudentProgressTimeline.tsx
 * ---------------------------------------------------------
 * STUDENT PROGRESSION TIMELINE PAGE
 * ---------------------------------------------------------
 *
 * Visualizes a learner's academic journey from StudentPromotion
 * records generated by the cumulative report engine.
 *
 * Compact golden enhancement:
 * - Original A4 print design is preserved.
 * - Screen/mobile preview now follows the compact golden standard.
 * - Top strip is compact: status dot + title + expand + more.
 * - Summary chips appear only on screen, outside the print document.
 * - Cards remain readable on small screens.
 * - Table overflow is isolated inside the component.
 * - No dashboard horizontal overflow.
 *
 * Route-shell safety:
 * - header is optional so this component can be registered in RolePortalShell routes.
 * - When opened without report props, it shows a compact golden empty state instead
 *   of failing TypeScript because RouteProps do not include header.
 *
 * Workspace source fix:
 * - Resolves the active school/branch from eleeveon_open_workspace first.
 * - Falls back to active membership, ActiveBranchContext, settings, then storage.
 * - Prevents stale data after role/workspace switching.
 *
 * Media source fix:
 * - School logo is resolved from mediaAssets via mediaAssetUtils first.
 * - Uses the same object-argument media lookup pattern as StudentReports.tsx.
 * - Loads school/branch/schoolBranchSettings rows like StudentReports before resolving media.
 * - Passes the resolved URL into ReportHeader as branding.logo, not branding.logoUrl.
 * - Falls back to legacy school.logo/settings logo strings only when no media asset exists.
 */

import React, { useEffect, useMemo, useState } from "react";

import { useAccount } from "../../../context/account-context";
import { useSettings } from "../../../context/settings-context";
import { useActiveBranch } from "../../../context/active-branch-context";
import { useActiveMembership } from "../../../context/active-membership-context";
import { listActiveLocal } from "../../../lib/sync/syncUtils";

import {
  db,
  type AcademicPeriod,
  type AcademicStructure,
  type Branch,
  type Class,
  type School,
  type SchoolBranchSetting,
  type Student,
} from "../../../lib/db/db";

import ReportHeader from "./components/ReportHeader";

import type { StudentProgressionStep } from "./engine/cumulative-report-types";
import type { ReportHeaderData } from "./engine/report-types";

import {
  MediaOwners,
  MediaFieldKeys,
  getMediaObjectUrl,
  getOwnerFieldMediaAsset,
  revokeMediaObjectUrl,
} from "../../../lib/media/mediaAssetUtils";

import { useDataRevision } from "../../../hooks/useDataRevision";
import { useBackgroundLoader } from "../../../hooks/useBackgroundLoader";
// ======================================================
// PAGE TYPES
// ======================================================

type RouteProps = {
  navigate?: (key: string) => void;
};

type TenantRow = {
  accountId?: string;
  schoolId?: number | string | null;
  branchId?: number | string | null;
  active?: boolean;
  isDeleted?: boolean;
};

type SchoolRow = {
  accountId?: string;
  id?: number;
  active?: boolean;
  isDeleted?: boolean;
};

type BranchRow = {
  accountId?: string;
  schoolId?: number | string | null;
  id?: number;
  active?: boolean;
  isDeleted?: boolean;
};

type OpenWorkspaceSession = {
  membership?: Record<string, any> | null;
  membershipId?: string | null;
  role?: string | null;
  schoolId?: number | string | null;
  branchId?: number | string | null;
  openedAt?: number;
};

type PromotionRow = TenantRow & {
  id?: number;
  studentId?: number;
  snapshotId?: number;
  fromClassId?: number;
  toClassId?: number;
  classId?: number;
  previousClassId?: number;
  promotedClassId?: number;
  fromAcademicPeriodId?: number;
  toAcademicPeriodId?: number;
  academicPeriodId?: number;
  previousAcademicPeriodId?: number;
  promotedAcademicPeriodId?: number;
  fromAcademicStructureId?: number;
  toAcademicStructureId?: number;
  academicStructureId?: number;
  previousAcademicStructureId?: number;
  promotedAcademicStructureId?: number;
  average?: number;
  recommendation?: string;
  finalDecision?: string;
  decision?: string;
  status?: string;
  note?: string;
  createdAt?: string | number;
  updatedAt?: string | number;
};

const OPEN_WORKSPACE_KEY = "eleeveon_open_workspace";

const TIMELINE_MEDIA_OWNER_SCHOOLS = String((MediaOwners as any).SCHOOLS || "schools");
const TIMELINE_MEDIA_OWNER_BRANCHES = String((MediaOwners as any).BRANCHES || "branches");
const TIMELINE_MEDIA_OWNER_SETTINGS = String(
  (MediaOwners as any).SCHOOL_BRANCH_SETTINGS ||
    (MediaOwners as any).SCHOOL_BRANCHES_SETTINGS ||
    "schoolBranchSettings"
);
const TIMELINE_FIELD_LOGO = String((MediaFieldKeys as any).LOGO || "logo");

function safeMediaString(value?: string | null) {
  const media = String(value || "");
  if (!media) return "";
  if (media.startsWith("blob:")) return "";
  if (media.startsWith("data:image/")) return "";
  return media;
}

function hasOwn(row: any, key: string) {
  return !!row && Object.prototype.hasOwnProperty.call(row, key);
}

function fallbackMediaValue(row: any, stringField: string, mediaIdField?: string) {
  if (!row) return "";

  // If the new mediaId field exists but is empty/null/0, treat that as intentional removal.
  // This prevents old legacy string fields from reviving deleted media on reports.
  if (mediaIdField && hasOwn(row, mediaIdField) && !cleanId(row[mediaIdField])) return "";

  return safeMediaString(row[stringField]);
}

function safeStorageRead(key: string) {
  if (typeof window === "undefined") return null;

  try {
    return window.localStorage.getItem(key) || window.sessionStorage.getItem(key);
  } catch {
    return null;
  }
}

function safeJsonRead<T>(key: string): T | null {
  const raw = safeStorageRead(key);
  if (!raw) return null;

  try {
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

function readOpenWorkspaceSession() {
  return safeJsonRead<OpenWorkspaceSession>(OPEN_WORKSPACE_KEY);
}

function cleanText(value: unknown) {
  return String(value || "").trim();
}

function cleanId(value: unknown) {
  const parsed = Number(value || 0);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
}

function sameId(a: unknown, b: unknown) {
  const left = cleanId(a);
  const right = cleanId(b);
  return left > 0 && right > 0 && left === right;
}

function accountMatches(rowAccountId: unknown, selectedAccountId?: string | null) {
  if (!selectedAccountId) return true;
  if (!rowAccountId) return true;
  return String(rowAccountId) === String(selectedAccountId);
}

function rowIsUsable(row: TenantRow) {
  return !!row && row.isDeleted !== true && row.active !== false;
}

async function activeRows<T>(tableName: string): Promise<T[]> {
  return ((await listActiveLocal(tableName as any)) || []) as T[];
}

function pickName<T extends { id?: number; name?: string; fullName?: string }>(rows: T[], id?: number) {
  if (!id) return "";
  const row = rows.find((item) => item.id === id);
  return cleanText(row?.name || row?.fullName);
}

function normalizeDecision(value: unknown) {
  const decision = cleanText(value).toLowerCase();
  if (decision.includes("graduat")) return "graduate";
  if (decision.includes("repeat")) return "repeat";
  if (decision.includes("promot")) return "promote";
  if (decision.includes("pass")) return "promote";
  return decision || "promote";
}

// ======================================================
// PROPS
// ======================================================

type Props = {
  steps?: StudentProgressionStep[];
  header?: ReportHeaderData;
  studentName?: string;
  compact?: boolean;
  pageBreakAfter?: boolean;
  mobilePreview?: boolean;
};

// ======================================================
// HELPERS
// ======================================================

const formatNumber = (value?: number, decimals = 1) => {
  if (value == null || Number.isNaN(value)) return "0";
  return Number(value).toFixed(decimals);
};

const decisionLabel = (value?: string) => {
  if (!value) return "-";
  return value.charAt(0).toUpperCase() + value.slice(1);
};

const decisionTone = (value?: string) => {
  if (value === "promote") return "#16a34a";
  if (value === "repeat") return "#dc2626";
  if (value === "graduate") return "#2563eb";
  return "#111827";
};

const decisionBg = (value?: string) => {
  if (value === "promote") return "rgba(22,163,74,0.10)";
  if (value === "repeat") return "rgba(220,38,38,0.10)";
  if (value === "graduate") return "rgba(37,99,235,0.10)";
  return "rgba(17,24,39,0.06)";
};

const stepKey = (step: StudentProgressionStep, index: number) => {
  return String(step.id ?? step.snapshotId ?? index);
};

const fallbackHeader: ReportHeaderData = {
  branding: {
    schoolName: "Selected School",
    branchName: "Selected Branch",
    primaryColor: "var(--primary-color, #2563eb)",
    fontFamily: "Arial, sans-serif",
  } as any,
} as ReportHeaderData;

// ======================================================
// PAGE COMPONENT
// ======================================================

export default function StudentProgressTimelinePage(_: RouteProps) {
  const dataRevision = useDataRevision();

  const { accountId, authenticated, loading: accountLoading } = useAccount() as any;
  const { settings, loading: settingsLoading } = useSettings() as any;
  const { activeMembership } = useActiveMembership() as any;

  const {
    activeSchool,
    activeSchoolId,
    activeBranch,
    activeBranchId,
    loading: contextLoading,
  } = useActiveBranch() as any;

  const openWorkspace = useMemo(() => readOpenWorkspaceSession(), []);

  const selectedAccountId = useMemo(
    () =>
      cleanText(accountId) ||
      cleanText(openWorkspace?.membership?.accountId) ||
      cleanText(activeMembership?.accountId) ||
      cleanText(settings?.accountId),
    [accountId, activeMembership?.accountId, openWorkspace?.membership?.accountId, settings?.accountId]
  );

  const schoolId = useMemo(
    () =>
      cleanId(openWorkspace?.schoolId) ||
      cleanId(openWorkspace?.membership?.schoolId) ||
      cleanId(openWorkspace?.membership?.school?.id) ||
      cleanId(activeMembership?.schoolId) ||
      cleanId(activeMembership?.school?.id) ||
      cleanId(activeSchoolId) ||
      cleanId(activeSchool?.id) ||
      cleanId(settings?.schoolId) ||
      cleanId(safeStorageRead("activeSchoolId")),
    [
      activeMembership?.school?.id,
      activeMembership?.schoolId,
      activeSchool?.id,
      activeSchoolId,
      openWorkspace?.membership?.school?.id,
      openWorkspace?.membership?.schoolId,
      openWorkspace?.schoolId,
      settings?.schoolId,
    ]
  );

  const branchId = useMemo(
    () =>
      cleanId(openWorkspace?.branchId) ||
      cleanId(openWorkspace?.membership?.branchId) ||
      cleanId(openWorkspace?.membership?.schoolBranchId) ||
      cleanId(openWorkspace?.membership?.branch?.id) ||
      cleanId(activeMembership?.branchId) ||
      cleanId(activeMembership?.schoolBranchId) ||
      cleanId(activeMembership?.branch?.id) ||
      cleanId(activeBranchId) ||
      cleanId(activeBranch?.id) ||
      cleanId(settings?.branchId) ||
      cleanId(safeStorageRead("activeBranchId")),
    [
      activeBranch?.id,
      activeBranchId,
      activeMembership?.branch?.id,
      activeMembership?.branchId,
      activeMembership?.schoolBranchId,
      openWorkspace?.branchId,
      openWorkspace?.membership?.branch?.id,
      openWorkspace?.membership?.branchId,
      openWorkspace?.membership?.schoolBranchId,
      settings?.branchId,
    ]
  );

  const primary = cleanText(settings?.primaryColor) || "var(--primary-color, #2563eb)";

  const { loading, setLoading } = useBackgroundLoader();
  const [schools, setSchools] = useState<School[]>([]);
  const [branches, setBranches] = useState<Branch[]>([]);
  const [schoolBranchSettings, setSchoolBranchSettings] = useState<SchoolBranchSetting[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [classes, setClasses] = useState<Class[]>([]);
  const [periods, setPeriods] = useState<AcademicPeriod[]>([]);
  const [structures, setStructures] = useState<AcademicStructure[]>([]);
  const [promotions, setPromotions] = useState<PromotionRow[]>([]);
  const [timelineMediaUrls, setTimelineMediaUrls] = useState<string[]>([]);

  const [search, setSearch] = useState("");
  const [studentId, setStudentId] = useState<number | undefined>();
  const [filterDecision, setFilterDecision] = useState<"all" | "promote" | "repeat" | "graduate">("all");
  const [filterOpen, setFilterOpen] = useState(false);
  const [previewExpanded, setPreviewExpanded] = useState(false);

  const sameTenant = (row: TenantRow) =>
    accountMatches(row.accountId, selectedAccountId) &&
    sameId(row.schoolId, schoolId) &&
    sameId(row.branchId, branchId) &&
    rowIsUsable(row);

  const clearData = () => {
    timelineMediaUrls.forEach(revokeMediaObjectUrl);
    setTimelineMediaUrls([]);
    setSchools([]);
    setBranches([]);
    setSchoolBranchSettings([]);
    setStudents([]);
    setClasses([]);
    setPeriods([]);
    setStructures([]);
    setPromotions([]);
  };

  const resolveTimelineMediaUrl = async ({
    ownerTable,
    ownerLocalId,
    ownerCloudId,
    fieldKey,
    fallbackMediaId,
    nextUrls,
  }: {
    ownerTable: string;
    ownerLocalId?: number | string | null;
    ownerCloudId?: string | null;
    fieldKey: string;
    fallbackMediaId?: number | string | null;
    nextUrls: string[];
  }) => {
    const localId = cleanId(ownerLocalId);

    if (localId) {
      const ownedAsset = await getOwnerFieldMediaAsset({
        accountId: selectedAccountId || undefined,
        ownerTable,
        ownerLocalId: localId,
        ownerCloudId: ownerCloudId || undefined,
        fieldKey,
      });

      if (ownedAsset?.id && !(ownedAsset as any).isDeleted && (ownedAsset as any).active !== false) {
        const url = await getMediaObjectUrl(Number(ownedAsset.id));
        if (url) {
          nextUrls.push(url);
          return url;
        }
      }
    }

    const mediaId = cleanId(fallbackMediaId);
    if (!mediaId) return "";

    const fallbackAsset = await (db as any).mediaAssets?.get?.(mediaId);
    const belongsToOwner =
      fallbackAsset &&
      !fallbackAsset.isDeleted &&
      fallbackAsset.active !== false &&
      (!selectedAccountId || fallbackAsset.accountId === selectedAccountId) &&
      fallbackAsset.ownerTable === ownerTable &&
      fallbackAsset.fieldKey === fieldKey &&
      (!localId || String(fallbackAsset.ownerLocalId || "") === String(localId));

    if (!belongsToOwner) return "";

    const url = await getMediaObjectUrl(mediaId);
    if (url) nextUrls.push(url);
    return url || "";
  };

  const load = async () => {
    if (!authenticated || !selectedAccountId || !schoolId || !branchId) {
      clearData();
      setLoading(false);
      return;
    }

    try {
      setLoading(true);

      const [
        schoolRows,
        branchRows,
        settingRows,
        studentRows,
        classRows,
        periodRows,
        structureRows,
        promotionRows,
      ] = await Promise.all([
        db.schools.toArray(),
        db.branches.toArray(),
        db.schoolBranchSettings.toArray(),
        activeRows<Student>("students"),
        activeRows<Class>("classes"),
        activeRows<AcademicPeriod>("academicPeriods"),
        activeRows<AcademicStructure>("academicStructures"),
        activeRows<PromotionRow>("studentPromotions"),
      ]);

      const sameSchool = (row: SchoolRow) =>
        accountMatches(row.accountId, selectedAccountId) &&
        sameId(row.id, schoolId) &&
        row.isDeleted !== true &&
        row.active !== false;

      const sameBranch = (row: BranchRow) =>
        accountMatches(row.accountId, selectedAccountId) &&
        sameId(row.schoolId, schoolId) &&
        sameId(row.id, branchId) &&
        row.isDeleted !== true &&
        row.active !== false;

      const currentSchool =
        (schoolRows as School[]).find((row: any) => sameSchool(row)) ||
        (accountMatches(activeSchool?.accountId, selectedAccountId) && sameId(activeSchool?.id, schoolId)
          ? activeSchool
          : undefined);

      const currentBranch =
        (branchRows as Branch[]).find((row: any) => sameBranch(row)) ||
        (accountMatches(activeBranch?.accountId, selectedAccountId) &&
        sameId(activeBranch?.schoolId, schoolId) &&
        sameId(activeBranch?.id, branchId)
          ? activeBranch
          : undefined);

      const scopedSettings = (settingRows as SchoolBranchSetting[]).filter((row: any) => sameTenant(row));
      const nextMediaUrls: string[] = [];

      const currentSchoolWithMedia = currentSchool
        ? ({
            ...currentSchool,
            logo:
              (await resolveTimelineMediaUrl({
                ownerTable: TIMELINE_MEDIA_OWNER_SCHOOLS,
                ownerLocalId: currentSchool.id,
                ownerCloudId: (currentSchool as any).cloudId,
                fieldKey: TIMELINE_FIELD_LOGO,
                fallbackMediaId: (currentSchool as any).logoMediaId,
                nextUrls: nextMediaUrls,
              })) || fallbackMediaValue(currentSchool, "logo", "logoMediaId"),
          } as School)
        : undefined;

      const currentBranchWithMedia = currentBranch
        ? ({
            ...currentBranch,
            logo:
              (await resolveTimelineMediaUrl({
                ownerTable: TIMELINE_MEDIA_OWNER_BRANCHES,
                ownerLocalId: currentBranch.id,
                ownerCloudId: (currentBranch as any).cloudId,
                fieldKey: TIMELINE_FIELD_LOGO,
                fallbackMediaId: (currentBranch as any).logoMediaId,
                nextUrls: nextMediaUrls,
              })) || fallbackMediaValue(currentBranch, "logo", "logoMediaId"),
          } as Branch)
        : undefined;

      const scopedSettingsWithMedia = await Promise.all(
        scopedSettings.map(async (row: any) => ({
          ...row,
          logo:
            (await resolveTimelineMediaUrl({
              ownerTable: TIMELINE_MEDIA_OWNER_SETTINGS,
              ownerLocalId: row.id,
              ownerCloudId: row.cloudId,
              fieldKey: TIMELINE_FIELD_LOGO,
              fallbackMediaId: row.logoMediaId,
              nextUrls: nextMediaUrls,
            })) || fallbackMediaValue(row, "logo", "logoMediaId"),
        }))
      );

      timelineMediaUrls.forEach((url) => {
        if (!nextMediaUrls.includes(url)) revokeMediaObjectUrl(url);
      });

      setTimelineMediaUrls(nextMediaUrls);
      setSchools(currentSchoolWithMedia ? [currentSchoolWithMedia] : []);
      setBranches(currentBranchWithMedia ? [currentBranchWithMedia] : []);
      setSchoolBranchSettings(scopedSettingsWithMedia as SchoolBranchSetting[]);

      setStudents(
        studentRows
          .filter((row: any) => sameTenant(row))
          .sort((a, b) => cleanText(a.fullName).localeCompare(cleanText(b.fullName)))
      );
      setClasses(classRows.filter((row: any) => sameTenant(row)));
      setPeriods(periodRows.filter((row: any) => sameTenant(row)));
      setStructures(structureRows.filter((row: any) => sameTenant(row)));
      setPromotions(promotionRows.filter((row: any) => sameTenant(row)));
    } catch (error) {
      console.error("Failed to load progression timeline:", error);
      clearData();
      alert("Failed to load student progression timeline.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    authenticated,
    selectedAccountId,
    schoolId,
    branchId,
    activeMembership?.role,
    activeMembership?.schoolId,
    activeMembership?.branchId,
    activeMembership?.schoolBranchId,
    openWorkspace?.openedAt,
    openWorkspace?.membershipId,
    dataRevision,
  ]);

  useEffect(() => {
    return () => {
      timelineMediaUrls.forEach(revokeMediaObjectUrl);
    };
  }, [timelineMediaUrls]);

  const availableStudentIds = useMemo(() => {
    const ids = new Set<number>();
    promotions.forEach((row) => {
      if (row.studentId) ids.add(row.studentId);
    });
    return ids;
  }, [promotions]);

  const filteredStudents = useMemo(() => {
    const query = search.trim().toLowerCase();

    return students.filter((student) => {
      if (availableStudentIds.size && !availableStudentIds.has(student.id || 0)) return false;
      if (!query) return true;
      return `${student.fullName || ""} ${student.admissionNumber || ""}`.toLowerCase().includes(query);
    });
  }, [availableStudentIds, search, students]);

  const selectedStudent = useMemo(() => {
    if (studentId) return students.find((student) => student.id === studentId);
    return filteredStudents[0];
  }, [filteredStudents, studentId, students]);

  const selectedStudentPromotions = useMemo(() => {
    if (!selectedStudent?.id) return [];

    return promotions
      .filter((row) => sameId(row.studentId, selectedStudent.id))
      .filter((row) => filterDecision === "all" || normalizeDecision(row.finalDecision || row.decision || row.status) === filterDecision)
      .sort((a, b) => Number(a.createdAt || a.updatedAt || 0) - Number(b.createdAt || b.updatedAt || 0));
  }, [filterDecision, promotions, selectedStudent?.id]);

  const steps = useMemo<StudentProgressionStep[]>(() => {
    return selectedStudentPromotions.map((row, index) => {
      const fromClassId = cleanId(row.fromClassId || row.previousClassId || row.classId);
      const toClassId = cleanId(row.toClassId || row.promotedClassId);
      const fromPeriodId = cleanId(row.fromAcademicPeriodId || row.previousAcademicPeriodId || row.academicPeriodId);
      const toPeriodId = cleanId(row.toAcademicPeriodId || row.promotedAcademicPeriodId);
      const fromStructureId = cleanId(row.fromAcademicStructureId || row.previousAcademicStructureId || row.academicStructureId);
      const toStructureId = cleanId(row.toAcademicStructureId || row.promotedAcademicStructureId);
      const finalDecision = normalizeDecision(row.finalDecision || row.decision || row.status);

      const step: StudentProgressionStep = {
        id: `promotion-${row.id || `${row.studentId || selectedStudent?.id || 0}-${fromClassId || index + 1}`}`,
        studentId: cleanId(row.studentId || selectedStudent?.id),

        fromClassId: fromClassId || undefined,
        fromClassName: pickName(classes, fromClassId) || "Previous Class",

        toClassId: toClassId || undefined,
        toClassName: pickName(classes, toClassId) || decisionLabel(finalDecision),

        fromAcademicPeriodId: fromPeriodId || undefined,
        fromAcademicPeriodName: pickName(periods, fromPeriodId),

        toAcademicPeriodId: toPeriodId || undefined,
        toAcademicPeriodName: pickName(periods, toPeriodId),

        fromAcademicStructureId: fromStructureId || undefined,
        fromAcademicStructureName: pickName(structures, fromStructureId),

        toAcademicStructureId: toStructureId || undefined,
        toAcademicStructureName: pickName(structures, toStructureId),

        average: Number(row.average || 0),
        recommendation: normalizeDecision(row.recommendation || finalDecision) as StudentProgressionStep["recommendation"],
        finalDecision: finalDecision as StudentProgressionStep["finalDecision"],

        snapshotId: row.snapshotId,
        note: row.note,
        dateLabel: pickName(periods, fromPeriodId) || pickName(structures, fromStructureId),
        rawPromotion: row as any,
      };

      return step;
    });
  }, [classes, periods, selectedStudentPromotions, structures]);

  const reportSchool = useMemo(() => {
    return (
      schools.find((school: any) => sameId(school.id, schoolId)) ||
      (accountMatches(activeSchool?.accountId, selectedAccountId) && sameId(activeSchool?.id, schoolId)
        ? activeSchool
        : undefined) ||
      schools[0]
    );
  }, [activeSchool, schools, schoolId, selectedAccountId]);

  const reportBranch = useMemo(() => {
    return (
      branches.find((branch: any) => sameId(branch.id, branchId)) ||
      (accountMatches(activeBranch?.accountId, selectedAccountId) &&
      sameId(activeBranch?.schoolId, schoolId) &&
      sameId(activeBranch?.id, branchId)
        ? activeBranch
        : undefined) ||
      branches[0]
    );
  }, [activeBranch, branches, branchId, schoolId, selectedAccountId]);

  const reportSetting = useMemo(() => {
    return schoolBranchSettings.find((setting: any) => sameId(setting.branchId, branchId)) || schoolBranchSettings[0];
  }, [branchId, schoolBranchSettings]);

  const header = useMemo<ReportHeaderData>(() => {
    const logo =
      safeMediaString((reportSetting as any)?.logo) ||
      safeMediaString((reportBranch as any)?.logo) ||
      safeMediaString((reportSchool as any)?.logo) ||
      safeMediaString(openWorkspace?.membership?.school?.logo) ||
      safeMediaString(settings?.schoolLogo) ||
      safeMediaString(settings?.logo);

    return {
      school: reportSchool as any,
      branch: reportBranch as any,
      schoolBranchSetting: reportSetting as any,
      branding: {
        schoolName:
          cleanText((reportSchool as any)?.name) ||
          cleanText(activeSchool?.name) ||
          cleanText(openWorkspace?.membership?.school?.name) ||
          cleanText(settings?.schoolName) ||
          "Selected School",
        branchName:
          cleanText((reportBranch as any)?.name) ||
          cleanText(activeBranch?.name) ||
          cleanText(openWorkspace?.membership?.branch?.name) ||
          cleanText(settings?.branchName) ||
          "Selected Branch",
        primaryColor: primary,
        fontFamily: cleanText(settings?.fontFamily) || "Arial, sans-serif",
        logo,
      } as any,
    } as ReportHeaderData;
  }, [
    activeBranch?.name,
    activeSchool?.name,
    openWorkspace?.membership?.branch?.name,
    openWorkspace?.membership?.school?.logo,
    openWorkspace?.membership?.school?.name,
    primary,
    reportBranch,
    reportSchool,
    reportSetting,
    settings?.branchName,
    settings?.fontFamily,
    settings?.logo,
    settings?.schoolLogo,
    settings?.schoolName,
  ]);

  const promoted = steps.filter((step) => step.finalDecision === "promote").length;
  const repeated = steps.filter((step) => step.finalDecision === "repeat").length;
  const graduated = steps.filter((step) => step.finalDecision === "graduate").length;
  const activeFilterCount = [studentId, filterDecision !== "all" ? filterDecision : undefined].filter(Boolean).length;

  if (accountLoading || contextLoading || settingsLoading || loading) {
    return <TimelineState primary={primary} title="Opening timeline..." text="Checking workspace, students and promotion history." />;
  }

  if (!authenticated || !selectedAccountId) {
    return <TimelineState primary={primary} title="Sign in required" text="You must sign in before viewing student progression timelines." />;
  }

  if (!schoolId || !branchId) {
    return <TimelineState primary={primary} title="Branch workspace required" text="Student progression timelines belong to one active school branch." />;
  }

  return (
    <main className={`spt-page ${previewExpanded ? "expanded" : ""}`} style={{ "--spt-primary": primary } as React.CSSProperties}>
      <style>{pageCss}</style>

      <section className="spt-page-toolbar">
        <span className={`spt-status-dot ${steps.length ? "green" : "gray"}`} />

        <label className="spt-page-search">
          <span>⌕</span>
          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search students..."
          />
        </label>

        <button type="button" className="spt-page-primary" onClick={load} title="Refresh" aria-label="Refresh">
          ↻
        </button>

        <button
          type="button"
          className={`spt-page-icon ${activeFilterCount ? "active" : ""}`}
          onClick={() => setFilterOpen(true)}
          title="Filters"
          aria-label="Filters"
        >
          <SliderIcon />
          {activeFilterCount ? <b>{activeFilterCount}</b> : null}
        </button>

        <button
          type="button"
          className="spt-page-icon"
          onClick={() => setPreviewExpanded((prev) => !prev)}
          title={previewExpanded ? "Fit preview" : "Expand preview"}
          aria-label={previewExpanded ? "Fit preview" : "Expand preview"}
        >
          {previewExpanded ? "↙" : "↗"}
        </button>
      </section>

      {activeFilterCount > 0 && (
        <section className="spt-page-chips">
          {selectedStudent && (
            <button type="button" onClick={() => setStudentId(undefined)}>
              Student: {selectedStudent.fullName} ×
            </button>
          )}
          {filterDecision !== "all" && (
            <button type="button" onClick={() => setFilterDecision("all")}>
              Decision: {decisionLabel(filterDecision)} ×
            </button>
          )}
        </section>
      )}

      <section className="spt-page-summary">
        <div>
          <strong>{steps.length}</strong>
          <span>timeline record(s)</span>
        </div>
        <p>{selectedStudent?.fullName || "Select student"} · {header.branding?.branchName || "Branch"}</p>
      </section>

      <section className="spt-page-chips stats">
        <button type="button">Students: {filteredStudents.length}</button>
        <button type="button">Promoted: {promoted}</button>
        <button type="button">Repeated: {repeated}</button>
        <button type="button">Graduated: {graduated}</button>
      </section>

      <div className="spt-page-layout">
        <aside className="spt-student-list">
          {filteredStudents.map((student) => (
            <button
              key={student.id}
              type="button"
              className={`spt-student-row ${selectedStudent?.id === student.id ? "active" : ""}`}
              onClick={() => setStudentId(student.id)}
            >
              <span className="spt-avatar">{cleanText(student.fullName).slice(0, 1).toUpperCase() || "S"}</span>
              <span>
                <strong>{student.fullName}</strong>
                <small>{student.admissionNumber || "No admission no."}</small>
              </span>
              <i>›</i>
            </button>
          ))}

          {!filteredStudents.length && (
            <section className="spt-empty-mini">
              <strong>No students found</strong>
              <span>No progression records match your search.</span>
            </section>
          )}
        </aside>

        <section className="spt-report-panel">
          {selectedStudent ? (
            <StudentProgressionTimelineReport
              steps={steps}
              header={header}
              studentName={selectedStudent.fullName}
              compact={false}
              pageBreakAfter={false}
              mobilePreview
            />
          ) : (
            <section className="spt-empty-mini large">
              <strong>No timeline selected</strong>
              <span>Select a student to preview the progression timeline.</span>
            </section>
          )}
        </section>
      </div>

      {filterOpen && (
        <div className="spt-page-sheet-backdrop" role="dialog" aria-modal="true">
          <section className="spt-page-sheet">
            <div className="spt-page-sheet-head">
              <div>
                <h2>Filters</h2>
                <p>Choose student and decision scope. School and branch stay locked.</p>
              </div>
              <button type="button" onClick={() => setFilterOpen(false)}>✕</button>
            </div>

            <div className="spt-page-form">
              <label>
                <span>Student</span>
                <select value={studentId || ""} onChange={(event) => setStudentId(cleanId(event.target.value) || undefined)}>
                  <option value="">Auto select</option>
                  {filteredStudents.map((student) => (
                    <option key={student.id} value={student.id}>{student.fullName}</option>
                  ))}
                </select>
              </label>

              <label>
                <span>Decision</span>
                <select value={filterDecision} onChange={(event) => setFilterDecision(event.target.value as any)}>
                  <option value="all">All decisions</option>
                  <option value="promote">Promoted</option>
                  <option value="repeat">Repeated</option>
                  <option value="graduate">Graduated</option>
                </select>
              </label>
            </div>

            <div className="spt-page-sheet-actions">
              <button type="button" onClick={() => { setStudentId(undefined); setFilterDecision("all"); }}>Clear</button>
              <button type="button" className="primary" onClick={() => setFilterOpen(false)}>Apply</button>
            </div>
          </section>
        </div>
      )}
    </main>
  );
}

function TimelineState({ primary, title, text }: { primary: string; title: string; text: string }) {
  return (
    <main className="spt-page" style={{ "--spt-primary": primary } as React.CSSProperties}>
      <style>{pageCss}</style>
      <section className="spt-page-state">
        <div className="spt-page-spinner" />
        <h2>{title}</h2>
        <p>{text}</p>
      </section>
    </main>
  );
}

function SliderIcon() {
  return (
    <svg className="spt-page-slider" viewBox="0 0 24 24" aria-hidden="true">
      <path d="M4 7h9" />
      <path d="M17 7h3" />
      <circle cx="15" cy="7" r="2" />
      <path d="M4 17h3" />
      <path d="M11 17h9" />
      <circle cx="9" cy="17" r="2" />
    </svg>
  );
}

// ======================================================
// REPORT RENDERER
// ======================================================

function StudentProgressionTimelineReport({
  steps = [],
  header,
  studentName,
  compact = false,
  pageBreakAfter = true,
  mobilePreview = true,
}: Props = {}) {
  const safeHeader = header || fallbackHeader;
  const noReportData = !header;

  const branding = safeHeader.branding || fallbackHeader.branding;
  const primary = branding.primaryColor || "var(--primary-color)";

  const [previewExpanded, setPreviewExpanded] = useState(false);
  const [moreOpen, setMoreOpen] = useState(false);
  const [openCards, setOpenCards] = useState<Record<string, boolean>>({});

  const promoted = useMemo(
    () => steps.filter((step) => step.finalDecision === "promote").length,
    [steps]
  );

  const repeated = useMemo(
    () => steps.filter((step) => step.finalDecision === "repeat").length,
    [steps]
  );

  const graduated = useMemo(
    () => steps.filter((step) => step.finalDecision === "graduate").length,
    [steps]
  );

  const toggleCard = (key: string) => {
    setOpenCards((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  if (noReportData) {
    return (
      <div className="spt-shell route-empty" style={{ "--spt-primary": primary } as React.CSSProperties}>
        <style>{css}</style>

        <div className="spt-toolbar route-visible report-no-print">
          <span className="spt-status-dot gray" />

          <div className="spt-toolbar-main">
            <strong>Student Progression Timeline</strong>
            <span>Open this timeline from a generated cumulative report.</span>
          </div>

          <button type="button" className="spt-toolbar-icon primary" onClick={() => window.print()} title="Print" aria-label="Print">
            🖨
          </button>
        </div>

        <section className="spt-route-empty-card">
          <div className="spt-route-empty-icon">📈</div>
          <h2>No timeline selected</h2>
          <p>
            This component is ready for report rendering, but it needs progression steps and a report header from the cumulative report engine.
          </p>
        </section>
      </div>
    );
  }

  const page: React.CSSProperties = {
    width: "210mm",
    minHeight: "297mm",
    margin: "0 auto 20px",
    padding: compact ? "9mm" : "11mm",
    boxSizing: "border-box",
    background: "#fff",
    color: "#111",
    fontFamily: branding.fontFamily || "Arial, sans-serif",
    border: "1px solid #e5e5e5",
    position: "relative",
    overflow: "hidden",
    pageBreakAfter: pageBreakAfter ? "always" : "auto",
  };

  const table: React.CSSProperties = {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: compact ? 8.5 : 9.5,
  };

  const th: React.CSSProperties = {
    border: "1px solid #222",
    padding: compact ? 3 : 5,
    background: primary,
    color: "#fff",
    textAlign: "center",
    fontWeight: 800,
    lineHeight: 1.15,
    whiteSpace: "nowrap",
  };

  const td: React.CSSProperties = {
    border: "1px solid #222",
    padding: compact ? 3 : 5,
    verticalAlign: "middle",
    lineHeight: 1.2,
  };

  const summaryCard: React.CSSProperties = {
    border: "1px solid #ddd",
    borderRadius: 12,
    padding: compact ? 8 : 10,
    background: "#fafafa",
  };

  const reportPage = (
    <section
      className="print-page report-page-break student-progression-timeline-page spt-a4-page"
      style={page}
    >
      <ReportHeader
        header={safeHeader}
        title="Student Progression Timeline"
        subtitle={
          studentName
            ? `${studentName} • ${steps.length} Progression Records`
            : `${steps.length} Progression Records`
        }
        orientation="portrait"
        compact={compact}
      />

      <div className="spt-summary-print-grid">
        <div style={summaryCard}>
          <div className="spt-summary-label">Records</div>
          <div className="spt-summary-value" style={{ color: primary }}>
            {steps.length}
          </div>
        </div>

        <div style={summaryCard}>
          <div className="spt-summary-label">Promoted</div>
          <div className="spt-summary-value" style={{ color: "#16a34a" }}>
            {promoted}
          </div>
        </div>

        <div style={summaryCard}>
          <div className="spt-summary-label">Repeated</div>
          <div className="spt-summary-value" style={{ color: "#dc2626" }}>
            {repeated}
          </div>
        </div>

        <div style={summaryCard}>
          <div className="spt-summary-label">Graduated</div>
          <div className="spt-summary-value" style={{ color: "#2563eb" }}>
            {graduated}
          </div>
        </div>
      </div>

      <div
        className="spt-print-timeline"
        style={{ borderLeftColor: primary }}
      >
        {steps.map((step, index) => {
          const key = stepKey(step, index);
          const isOpen = openCards[key];

          return (
            <div
              key={key}
              className="spt-print-card"
              style={{ background: decisionBg(step.finalDecision) }}
            >
              <div
                className="spt-print-dot"
                style={{ background: decisionTone(step.finalDecision) }}
              />

              <button
                type="button"
                className="spt-print-card-head report-no-print"
                onClick={() => toggleCard(key)}
              >
                <span>View Details</span>
              </button>

              <div className="spt-card-layout">
                <div>
                  <div className="spt-title">
                    {index + 1}. {step.fromClassName || "Class"} → {step.toClassName || decisionLabel(step.finalDecision)}
                  </div>

                  <div className="spt-period-line">
                    {step.fromAcademicPeriodName || step.fromAcademicStructureName || "-"}
                    {" → "}
                    {step.toAcademicPeriodName || step.toAcademicStructureName || "-"}
                  </div>

                  {step.note && (
                    <div className={`spt-note ${isOpen ? "open" : ""}`}>
                      {step.note}
                    </div>
                  )}
                </div>

                <div
                  className="spt-decision-pill"
                  style={{
                    borderColor: decisionTone(step.finalDecision),
                    color: decisionTone(step.finalDecision),
                  }}
                >
                  {decisionLabel(step.finalDecision)}
                </div>
              </div>

              <div className="spt-mini-grid">
                <div>
                  <strong>Average:</strong>{" "}
                  {step.average != null ? `${formatNumber(step.average, 1)}%` : "-"}
                </div>

                <div>
                  <strong>Recommended:</strong> {decisionLabel(step.recommendation)}
                </div>

                <div>
                  <strong>Snapshot:</strong> {step.snapshotId || "-"}
                </div>
              </div>
            </div>
          );
        })}

        {!steps.length && (
          <div className="spt-empty-box">
            No progression records found for this student.
          </div>
        )}
      </div>

      <div className="spt-table-wrap">
        <table style={table}>
          <thead>
            <tr>
              <th style={th}>#</th>
              <th style={th}>From Class</th>
              <th style={th}>To Class</th>
              <th style={th}>From Period</th>
              <th style={th}>To Period</th>
              <th style={th}>Average</th>
              <th style={th}>Recommendation</th>
              <th style={th}>Final Decision</th>
            </tr>
          </thead>

          <tbody>
            {steps.map((step, index) => (
              <tr key={`${stepKey(step, index)}-table`}>
                <td style={{ ...td, textAlign: "center" }}>{index + 1}</td>
                <td style={td}>{step.fromClassName || "-"}</td>
                <td style={td}>{step.toClassName || "-"}</td>
                <td style={td}>{step.fromAcademicPeriodName || "-"}</td>
                <td style={td}>{step.toAcademicPeriodName || "-"}</td>
                <td style={{ ...td, textAlign: "center", fontWeight: 800 }}>
                  {step.average != null ? `${formatNumber(step.average, 1)}%` : "-"}
                </td>
                <td style={{ ...td, textAlign: "center" }}>
                  {decisionLabel(step.recommendation)}
                </td>
                <td
                  style={{
                    ...td,
                    textAlign: "center",
                    fontWeight: 900,
                    color: decisionTone(step.finalDecision),
                  }}
                >
                  {decisionLabel(step.finalDecision)}
                </td>
              </tr>
            ))}

            {!steps.length && (
              <tr>
                <td style={{ ...td, textAlign: "center", padding: 14 }} colSpan={8}>
                  No progression records found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <div
        className="spt-footer"
        style={{ borderTopColor: primary }}
      >
        <span>Official progression timeline generated for {branding.schoolName}</span>
        <span>Powered by Eleeveon School Management System</span>
      </div>
    </section>
  );

  if (!mobilePreview) {
    return (
      <div className="spt-shell">
        <style>{css}</style>
        {reportPage}
      </div>
    );
  }

  return (
    <div className={`spt-shell ${previewExpanded ? "expanded" : ""}`} style={{ "--spt-primary": primary } as React.CSSProperties}>
      <style>{css}</style>

      <div className="spt-toolbar report-no-print">
        <span className={`spt-status-dot ${steps.length ? "green" : "gray"}`} />

        <div className="spt-toolbar-main">
          <strong>{studentName || "Progression Timeline"}</strong>
          <span>
            {steps.length} record(s) · {promoted} promoted · {repeated} repeated
          </span>
        </div>

        <button
          type="button"
          className="spt-toolbar-icon primary"
          onClick={() => setPreviewExpanded((prev) => !prev)}
          title={previewExpanded ? "Fit preview" : "Expand preview"}
          aria-label={previewExpanded ? "Fit preview" : "Expand preview"}
        >
          {previewExpanded ? "↙" : "↗"}
        </button>

        <button
          type="button"
          className="spt-toolbar-icon"
          onClick={() => setMoreOpen(true)}
          title="More"
          aria-label="More"
        >
          ⋯
        </button>
      </div>

      <div className="spt-screen-chips report-no-print">
        <button type="button">Records: {steps.length}</button>
        <button type="button">Promoted: {promoted}</button>
        <button type="button">Repeated: {repeated}</button>
        <button type="button">Graduated: {graduated}</button>
      </div>

      <div className="spt-preview-scroll report-screen-scroll">
        <div className="spt-preview-scale">
          {reportPage}
        </div>
      </div>

      {moreOpen && (
        <div className="spt-sheet-backdrop report-no-print" role="dialog" aria-modal="true">
          <section className="spt-sheet">
            <div className="spt-sheet-head">
              <div>
                <h2>Timeline</h2>
                <p>{steps.length} record(s) for {studentName || "selected student"}.</p>
              </div>
              <button type="button" onClick={() => setMoreOpen(false)} aria-label="Close">✕</button>
            </div>

            <div className="spt-menu-list">
              <button type="button" onClick={() => { setPreviewExpanded(false); setMoreOpen(false); }}>
                <span>↙</span>
                <b>Fit preview</b>
                <small>Scale A4 page inside the dashboard</small>
              </button>

              <button type="button" onClick={() => { setPreviewExpanded(true); setMoreOpen(false); }}>
                <span>↗</span>
                <b>Expand preview</b>
                <small>Show the full A4 width with horizontal scroll</small>
              </button>

              <button type="button" onClick={() => window.print()}>
                <span>🖨</span>
                <b>Print</b>
                <small>Print or save the timeline as PDF</small>
              </button>
            </div>
          </section>
        </div>
      )}
    </div>
  );
}

// ======================================================
// CSS
// ======================================================


const pageCss = `
@keyframes sptPageSpin { to { transform: rotate(360deg); } }
.spt-page{min-height:100dvh;width:100%;max-width:100%;min-width:0;padding:calc(8px * var(--local-density-scale,1));padding-bottom:max(40px,env(safe-area-inset-bottom));background:radial-gradient(circle at top left,color-mix(in srgb,var(--spt-primary) 9%,transparent),transparent 30rem),var(--bg,#f7f8fb);color:var(--text,#111827);font-family:var(--font-family,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif);overflow-x:hidden}.spt-page *,.spt-page *::before,.spt-page *::after{box-sizing:border-box;min-width:0}.spt-page button,.spt-page input,.spt-page select{font:inherit;max-width:100%}.spt-page input,.spt-page select{width:100%;min-height:44px;border:1px solid var(--input-border,var(--border,rgba(0,0,0,.10)));border-radius:16px;padding:0 12px;background:var(--input-bg,var(--surface,#fff));color:var(--input-text,var(--text,#111827));outline:none;font-weight:750}.spt-page-toolbar,.spt-page-summary,.spt-student-row,.spt-report-panel,.spt-empty-mini,.spt-page-state,.spt-page-sheet{background:var(--card-bg,var(--surface,#fff));border:1px solid var(--border,rgba(0,0,0,.10));box-shadow:0 12px 28px rgba(15,23,42,.045)}.spt-page-state{min-height:min(420px,calc(100dvh - 32px));width:min(520px,100%);margin:0 auto;display:grid;place-items:center;align-content:center;gap:10px;padding:22px;border-radius:28px;text-align:center}.spt-page-spinner{width:38px;height:38px;border-radius:999px;border:4px solid color-mix(in srgb,var(--spt-primary) 18%,transparent);border-top-color:var(--spt-primary);animation:sptPageSpin .8s linear infinite}.spt-page-state h2{margin:0;font-size:22px;font-weight:1000;letter-spacing:-.04em}.spt-page-state p{max-width:34rem;margin:0;color:var(--muted,#64748b);font-size:13px;line-height:1.6}.spt-page-toolbar{display:grid;grid-template-columns:auto minmax(0,1fr) 42px 42px 42px;gap:8px;align-items:center;padding:8px;border-radius:24px}.spt-page-search{min-width:0;display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:8px;min-height:44px;padding:0 11px;border-radius:18px;background:color-mix(in srgb,var(--muted,#64748b) 7%,transparent)}.spt-page-search span{color:var(--muted,#64748b);font-size:17px;font-weight:1000}.spt-page-search input{min-height:42px;border:0;padding:0;border-radius:0;background:transparent;box-shadow:none}.spt-page-primary,.spt-page-icon{width:42px;height:42px;border:1px solid var(--border,rgba(0,0,0,.10));border-radius:999px;display:grid;place-items:center;background:var(--card-bg,var(--surface,#fff));color:var(--text,#111827);font-size:18px;font-weight:1000;cursor:pointer;box-shadow:0 10px 22px rgba(15,23,42,.045)}.spt-page-primary{border-color:var(--spt-primary);background:var(--spt-primary);color:#fff}.spt-page-icon{position:relative;color:var(--spt-primary);background:color-mix(in srgb,var(--spt-primary) 8%,var(--surface,#fff))}.spt-page-icon.active{background:var(--spt-primary);color:#fff}.spt-page-icon b{position:absolute;top:-4px;right:-4px;min-width:19px;height:19px;display:grid;place-items:center;border-radius:999px;background:#ef4444;color:#fff;font-size:10px;border:2px solid var(--card-bg,#fff)}.spt-page-slider{width:21px;height:21px;fill:none;stroke:currentColor;stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}.spt-page-chips{display:flex;gap:7px;overflow-x:auto;padding:8px 1px 0;scrollbar-width:none}.spt-page-chips::-webkit-scrollbar{display:none}.spt-page-chips button{flex:0 0 auto;min-height:31px;border:0;border-radius:999px;padding:0 10px;background:color-mix(in srgb,var(--spt-primary) 11%,transparent);color:var(--spt-primary);font-size:11px;font-weight:950;white-space:nowrap}.spt-page-summary{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:8px;padding:10px 12px;border-radius:20px}.spt-page-summary div{display:flex;align-items:baseline;gap:6px}.spt-page-summary strong{font-size:21px;font-weight:1000;letter-spacing:-.05em}.spt-page-summary span,.spt-page-summary p{color:var(--muted,#64748b);font-size:12px;font-weight:850}.spt-page-summary p{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.spt-page-layout{display:grid;gap:10px;margin-top:10px}.spt-student-list{display:grid;gap:7px;align-content:start}.spt-student-row{width:100%;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px;border-radius:22px;text-align:left;color:var(--text,#111827);cursor:pointer}.spt-student-row.active{border-color:color-mix(in srgb,var(--spt-primary) 32%,var(--border,rgba(0,0,0,.10)));box-shadow:0 16px 34px rgba(15,23,42,.07)}.spt-avatar{width:44px;height:44px;display:grid;place-items:center;border-radius:17px;background:var(--spt-primary);color:#fff;font-weight:1000}.spt-student-row span:nth-child(2),.spt-student-row strong,.spt-student-row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.spt-student-row strong{font-size:13px;font-weight:1000}.spt-student-row small{margin-top:3px;color:var(--muted,#64748b);font-size:11px;font-weight:800}.spt-student-row i{font-style:normal;color:var(--muted,#64748b);font-size:18px;font-weight:1000}.spt-report-panel{min-width:0;padding:8px;border-radius:24px;overflow:hidden}.spt-empty-mini{display:grid;place-items:center;align-content:center;gap:5px;min-height:110px;padding:14px;border-radius:20px;text-align:center}.spt-empty-mini.large{min-height:280px}.spt-empty-mini strong{font-size:15px;font-weight:1000}.spt-empty-mini span{color:var(--muted,#64748b);font-size:12px;font-weight:750}.spt-page-sheet-backdrop{position:fixed;inset:0;z-index:80;display:grid;place-items:end center;padding:10px;background:rgba(15,23,42,.50);backdrop-filter:blur(12px)}.spt-page-sheet{width:min(520px,100%);max-height:min(88dvh,760px);overflow-y:auto;padding:14px;border-radius:28px 28px 22px 22px}.spt-page-sheet-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding-bottom:12px}.spt-page-sheet-head h2{margin:0;font-size:21px;font-weight:1000;letter-spacing:-.05em}.spt-page-sheet-head p{margin:5px 0 0;color:var(--muted,#64748b);font-size:12px;line-height:1.5;font-weight:750}.spt-page-sheet-head button{width:38px;height:38px;border:1px solid var(--border,rgba(0,0,0,.10));border-radius:999px;background:var(--surface,#fff);color:var(--text,#111827);font-weight:1000}.spt-page-form{display:grid;gap:9px}.spt-page-form label{display:grid;gap:6px}.spt-page-form span{color:var(--muted,#64748b);font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.06em}.spt-page-sheet-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.spt-page-sheet-actions button{min-height:42px;border:1px solid var(--border,rgba(0,0,0,.10));border-radius:999px;padding:0 16px;background:color-mix(in srgb,var(--muted,#64748b) 8%,var(--surface,#fff));color:var(--text,#111827);font-size:12px;font-weight:950}.spt-page-sheet-actions button.primary{border-color:var(--spt-primary);background:var(--spt-primary);color:#fff}@media (min-width:980px){.spt-page{padding:12px}.spt-page-layout{grid-template-columns:minmax(240px,320px) minmax(0,1fr);align-items:start}.spt-student-list{max-height:calc(100dvh - 170px);overflow:auto;padding-right:2px}.spt-page-toolbar,.spt-page-summary,.spt-page-chips,.spt-page-layout{max-width:1280px;margin-left:auto;margin-right:auto}}@media (max-width:520px){.spt-page{padding:7px}.spt-page-toolbar{grid-template-columns:auto minmax(0,1fr) 40px 40px 40px;gap:6px;padding:6px}.spt-page-primary,.spt-page-icon{width:40px;height:40px}.spt-page-summary{display:grid}.spt-page-sheet-actions{display:grid}.spt-page-sheet-actions button{width:100%}}
`;

const css = `
.spt-shell {
  width: 100%;
  max-width: 100%;
  min-width: 0;
  overflow: hidden;
}


.spt-toolbar.route-visible {
  display: grid;
}

.spt-route-empty-card {
  min-height: min(360px, calc(100dvh - 28px));
  display: grid;
  place-items: center;
  align-content: center;
  gap: 10px;
  padding: 22px;
  border-radius: 28px;
  background: var(--card-bg, var(--surface, #fff));
  color: var(--text, #0f172a);
  border: 1px solid var(--border, rgba(148,163,184,.22));
  box-shadow: 0 18px 46px rgba(15,23,42,.07);
  text-align: center;
}

.spt-route-empty-icon {
  width: 58px;
  height: 58px;
  display: grid;
  place-items: center;
  border-radius: 22px;
  background: color-mix(in srgb, var(--spt-primary, var(--primary-color, #2563eb)) 12%, var(--surface, #fff));
  font-size: 28px;
}

.spt-route-empty-card h2 {
  margin: 0;
  color: var(--text, #0f172a);
  font-size: 22px;
  font-weight: 1000;
  letter-spacing: -.04em;
}

.spt-route-empty-card p {
  max-width: 34rem;
  margin: 0;
  color: var(--muted, #64748b);
  font-size: 13px;
  line-height: 1.6;
  font-weight: 750;
}

.spt-toolbar {
  display: none;
  grid-template-columns: auto minmax(0, 1fr) auto auto;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
  padding: 8px;
  border-radius: 24px;
  background: var(--card-bg, var(--surface, #fff));
  border: 1px solid var(--border, rgba(148,163,184,.22));
  box-shadow: 0 12px 28px rgba(15,23,42,.045);
}

.spt-status-dot {
  width: 10px;
  height: 10px;
  border-radius: 999px;
  display: inline-flex;
  box-shadow: 0 0 0 5px color-mix(in srgb, var(--spt-primary, var(--primary-color, #2563eb)) 12%, transparent);
}

.spt-status-dot.green {
  background: #22c55e;
}

.spt-status-dot.gray {
  background: var(--muted, #64748b);
}

.spt-toolbar-main {
  min-width: 0;
}

.spt-toolbar-main strong,
.spt-toolbar-main span {
  display: block;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.spt-toolbar-main strong {
  color: var(--text, #0f172a);
  font-size: 13px;
  font-weight: 1000;
  letter-spacing: -.02em;
}

.spt-toolbar-main span {
  margin-top: 2px;
  color: var(--muted, #64748b);
  font-size: 11px;
  font-weight: 800;
}

.spt-toolbar-icon {
  width: 40px;
  height: 40px;
  display: grid;
  place-items: center;
  border: 1px solid var(--border, rgba(148,163,184,.22));
  border-radius: 999px;
  background: var(--card-bg, var(--surface, #fff));
  color: var(--text, #0f172a);
  font-size: 17px;
  font-weight: 1000;
  cursor: pointer;
  box-shadow: 0 10px 22px rgba(15,23,42,.045);
}

.spt-toolbar-icon.primary {
  border-color: var(--spt-primary, var(--primary-color, #2563eb));
  background: var(--spt-primary, var(--primary-color, #2563eb));
  color: #fff;
  box-shadow: 0 12px 28px color-mix(in srgb, var(--spt-primary, var(--primary-color, #2563eb)) 22%, transparent);
}

.spt-screen-chips {
  display: none;
  gap: 7px;
  overflow-x: auto;
  padding: 0 1px 8px;
  scrollbar-width: none;
}

.spt-screen-chips::-webkit-scrollbar {
  display: none;
}

.spt-screen-chips button {
  flex: 0 0 auto;
  min-height: 31px;
  border: 0;
  border-radius: 999px;
  padding: 0 10px;
  background: color-mix(in srgb, var(--spt-primary, var(--primary-color, #2563eb)) 11%, transparent);
  color: var(--spt-primary, var(--primary-color, #2563eb));
  font-size: 11px;
  font-weight: 950;
  white-space: nowrap;
  cursor: default;
}

.spt-sheet-backdrop {
  position: fixed;
  inset: 0;
  z-index: 80;
  display: grid;
  place-items: end center;
  padding: 10px;
  background: rgba(15,23,42,.50);
  backdrop-filter: blur(12px);
}

.spt-sheet {
  width: min(520px, 100%);
  max-height: min(88dvh, 760px);
  overflow-y: auto;
  padding: 14px;
  border-radius: 28px 28px 22px 22px;
  background: var(--card-bg, var(--surface, #fff));
  color: var(--text, #0f172a);
  border: 1px solid var(--border, rgba(148,163,184,.22));
  box-shadow: 0 30px 90px rgba(15,23,42,.32);
}

.spt-sheet-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  padding-bottom: 12px;
}

.spt-sheet-head h2 {
  margin: 0;
  color: var(--text, #0f172a);
  font-size: 21px;
  font-weight: 1000;
  letter-spacing: -.05em;
}

.spt-sheet-head p {
  margin: 5px 0 0;
  color: var(--muted, #64748b);
  font-size: 12px;
  line-height: 1.5;
  font-weight: 750;
}

.spt-sheet-head button {
  width: 38px;
  height: 38px;
  border: 1px solid var(--border, rgba(148,163,184,.22));
  border-radius: 999px;
  background: var(--surface, #fff);
  color: var(--text, #0f172a);
  font-weight: 1000;
  cursor: pointer;
  flex: 0 0 auto;
}

.spt-menu-list {
  display: grid;
  gap: 8px;
}

.spt-menu-list button {
  width: 100%;
  display: grid;
  grid-template-columns: 42px minmax(0, 1fr);
  column-gap: 10px;
  align-items: center;
  min-height: 58px;
  border: 1px solid var(--border, rgba(148,163,184,.22));
  border-radius: 18px;
  padding: 9px;
  background: var(--surface, #fff);
  color: var(--text, #0f172a);
  text-align: left;
  cursor: pointer;
}

.spt-menu-list button span {
  grid-row: span 2;
  width: 42px;
  height: 42px;
  display: grid;
  place-items: center;
  border-radius: 16px;
  background: color-mix(in srgb, var(--spt-primary, var(--primary-color, #2563eb)) 10%, transparent);
  color: var(--spt-primary, var(--primary-color, #2563eb));
  font-weight: 1000;
}

.spt-menu-list button b,
.spt-menu-list button small {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.spt-menu-list button b {
  font-size: 13px;
  font-weight: 1000;
}

.spt-menu-list button small {
  margin-top: 2px;
  color: var(--muted, #64748b);
  font-size: 11px;
  font-weight: 750;
}

.spt-preview-scroll {
  width: 100%;
  max-width: 100%;
  min-width: 0;
  overflow-x: auto;
  overflow-y: visible;
  -webkit-overflow-scrolling: touch;
  padding: 8px;
  border-radius: 22px;
  background: color-mix(in srgb, var(--muted, #64748b) 8%, transparent);
  border: 1px solid var(--border, rgba(148,163,184,.18));
}

.spt-preview-scale {
  width: max-content;
  min-width: 100%;
  transform-origin: top left;
}

.spt-summary-print-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 6px;
  margin-bottom: 12px;
}

.spt-summary-print-grid > div {
  min-width: 0;
  overflow: hidden;
}

.spt-summary-label {
  display: block;
  max-width: 100%;
  font-size: 8px;
  line-height: 1.15;
  opacity: 0.72;
  font-weight: 900;
  white-space: normal;
  overflow-wrap: anywhere;
  word-break: break-word;
}

.spt-summary-value {
  margin-top: 3px;
  font-size: 18px;
  line-height: 1;
  font-weight: 900;
}

.spt-print-timeline {
  border-left: 4px solid;
  padding-left: 14px;
  display: grid;
  gap: 10px;
  margin-bottom: 14px;
}

.spt-print-card {
  position: relative;
  border: 1px solid #ddd;
  border-radius: 14px;
  padding: 10px;
  break-inside: avoid;
}

.spt-print-dot {
  position: absolute;
  left: -25px;
  top: 14px;
  width: 18px;
  height: 18px;
  border-radius: 999px;
  border: 3px solid #fff;
  box-shadow: 0 0 0 1px #ddd;
}

.spt-print-card-head {
  display: none;
}

.spt-card-layout {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 10px;
  align-items: start;
}

.spt-title {
  font-size: 11.5px;
  font-weight: 900;
  overflow-wrap: anywhere;
}

.spt-period-line {
  margin-top: 4px;
  font-size: 9.5px;
  opacity: 0.78;
  font-weight: 650;
  overflow-wrap: anywhere;
}

.spt-note {
  margin-top: 6px;
  font-size: 9.5px;
  line-height: 1.35;
  overflow-wrap: anywhere;
}

.spt-decision-pill {
  min-width: 90px;
  text-align: center;
  border-radius: 999px;
  padding: 6px 10px;
  background: #fff;
  border: 1px solid;
  font-weight: 900;
  font-size: 9.5px;
}

.spt-mini-grid {
  margin-top: 8px;
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 6px;
  font-size: 9px;
}

.spt-mini-grid div {
  min-width: 0;
  overflow-wrap: anywhere;
}

.spt-empty-box {
  padding: 20px;
  border: 1px dashed #bbb;
  border-radius: 12px;
  text-align: center;
  font-weight: 700;
}

.spt-table-wrap {
  width: 100%;
  max-width: 100%;
  overflow-x: auto;
}

.spt-footer {
  margin-top: 10px;
  border-top: 2px solid;
  padding-top: 5px;
  display: flex;
  justify-content: space-between;
  gap: 10px;
  font-size: 8.5px;
  color: #555;
}

@media screen and (max-width: 720px) {
  .spt-summary-print-grid {
    gap: 4px;
  }

  .spt-summary-print-grid > div {
    padding: 6px !important;
    border-radius: 9px !important;
  }

  .spt-summary-label {
    font-size: 6.8px;
    letter-spacing: -0.15px;
  }

  .spt-summary-value {
    font-size: 14px;
  }

  .spt-toolbar {
    display: grid;
  }

  .spt-screen-chips {
    display: flex;
  }

  .spt-shell:not(.expanded) .spt-preview-scroll {
    overflow: hidden;
    max-height: 82vh;
  }

  .spt-shell:not(.expanded) .spt-preview-scale {
    width: 210mm;
    transform: scale(calc((100vw - 28px) / 793.7008));
    transform-origin: top left;
  }

  .spt-shell:not(.expanded) .spt-preview-scroll::after {
    content: "";
    display: block;
    height: calc(1122.5197px * ((100vw - 28px) / 793.7008));
  }

  .spt-shell.expanded .spt-preview-scroll {
    overflow-x: auto;
    max-height: none;
  }

  .spt-shell.expanded .spt-preview-scale {
    transform: none;
  }

  .spt-print-card-head {
    display: inline-flex;
    margin-bottom: 8px;
    border: 0;
    border-radius: 999px;
    padding: 5px 9px;
    background: rgba(255,255,255,.72);
    color: #111827;
    font-size: 9px;
    font-weight: 900;
  }

  .spt-card-layout {
    grid-template-columns: minmax(0, 1fr);
  }

  .spt-decision-pill {
    width: fit-content;
    min-width: 0;
  }

  .spt-note:not(.open) {
    display: none;
  }

  .spt-mini-grid {
    grid-template-columns: minmax(0, 1fr);
  }
}

@media print {
  .spt-shell,
  .spt-preview-scroll,
  .spt-preview-scale {
    display: contents !important;
    transform: none !important;
    overflow: visible !important;
    padding: 0 !important;
    border: 0 !important;
    background: transparent !important;
  }

  .spt-toolbar,
  .spt-screen-chips,
  .spt-sheet-backdrop,
  .spt-print-card-head {
    display: none !important;
  }

  .spt-note {
    display: block !important;
  }
}
`;
